### ISSUE TITLE
Built-in node failing on all files for the last few versions

### ISSUE THREAD

**Issue by Ulrar** [HaveAGitGat/Tdarr#1068]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
For a few weeks now, the built-in node has been unable to convert any files.
A windows node however does convert those same files just fine.

**To Reproduce**
Not sure

**Expected behavior**
Convert files on any node

**Please provide the following information:**

Node config : 
```
{
  "nodeID": "<id>",
  "nodeName": "MyServer",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "platform_arch_isdocker": "linux_x64_docker_true",
  "processPid": 228,
  "cronPluginUpdate": "",
  "apiKey": "",
  "seededWorkerLimits": {},
  "uptime": 397458
}
```

Job :
```
2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:[Step W03] [C6] [Shows] Running Community plugin: 1.0.0: runClassicTranscodePlugin: Classic Transcode Plugin FFMPEG_CPU

2

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Scanning original library file

3

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:{

4

2024-08-27T09:28:35.022Z "exifToolScan": true,

5

2024-08-27T09:28:35.022Z "mediaInfoScan": false,

6

2024-08-27T09:28:35.022Z "closedCaptionScan": false

7

2024-08-27T09:28:35.022Z }

8

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Loading source file: "/MyPath/MyFile.mkv"

9

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Scanning source file: "/MyPath/MyFile.mkv"

10

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Using cached scan results

11

2024-08-27T09:28:35.022Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Scan types: {

12

2024-08-27T09:28:35.022Z "exifToolScan": true,

13

2024-08-27T09:28:35.022Z "mediaInfoScan": false,

14

2024-08-27T09:28:35.022Z "closedCaptionScan": false

15

2024-08-27T09:28:35.022Z }

16

2024-08-27T09:28:35.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Loaded plugin inputs: {

17

2024-08-27T09:28:35.023Z "pluginSourceId": "Community:Tdarr_Plugin_MC93_Migz1FFMPEG_CPU",

18

2024-08-27T09:28:35.023Z "force_conform": "true",

19

2024-08-27T09:28:35.023Z "enable_10bit": "true"

20

2024-08-27T09:28:35.023Z }

21

2024-08-27T09:28:35.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:No depedencies to install for Community:Tdarr_Plugin_MC93_Migz1FFMPEG_CPU

22

2024-08-27T09:28:35.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Scanning files using Node

23

2024-08-27T09:28:36.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:{

24

2024-08-27T09:28:36.023Z "processFile": true,

25

2024-08-27T09:28:36.023Z "preset": ",-map 0 -c:v libx265 -b:v 5248k -minrate 3673k -maxrate 6822k -bufsize 10496k -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le ",

26

2024-08-27T09:28:36.023Z "handBrakeMode": false,

27

2024-08-27T09:28:36.023Z "FFmpegMode": true,

28

2024-08-27T09:28:36.023Z "reQueueAfter": true,

29

2024-08-27T09:28:36.023Z "infoLog": "Container for output selected as mkv. \nCurrent bitrate = 10496 \nBitrate settings: \nTarget = 5248 \nMinimum = 3673 \nMaximum = 6822 \nFile is not hevc or vp9. Transcoding. \n",

30

2024-08-27T09:28:36.023Z "container": ".mkv",

31

2024-08-27T09:28:36.023Z "ffmpegMode": true,

32

2024-08-27T09:28:36.023Z "cliToUse": "ffmpeg"

33

2024-08-27T09:28:36.023Z }

34

2024-08-27T09:28:36.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:{

35

2024-08-27T09:28:36.023Z "processFile": true,

36

2024-08-27T09:28:36.023Z "preset": ",-map 0 -c:v libx265 -b:v 5248k -minrate 3673k -maxrate 6822k -bufsize 10496k -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le ",

37

2024-08-27T09:28:36.023Z "handBrakeMode": false,

38

2024-08-27T09:28:36.023Z "FFmpegMode": true,

39

2024-08-27T09:28:36.023Z "reQueueAfter": true,

40

2024-08-27T09:28:36.023Z "infoLog": "Container for output selected as mkv. \nCurrent bitrate = 10496 \nBitrate settings: \nTarget = 5248 \nMinimum = 3673 \nMaximum = 6822 \nFile is not hevc or vp9. Transcoding. \n",

41

2024-08-27T09:28:36.023Z "container": ".mkv"

42

2024-08-27T09:28:36.023Z }

43

2024-08-27T09:28:36.023Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Running tdarr-ffmpeg -i /MyPath/MyFile.mkv -map 0 -c:v libx265 -b:v 5248k -minrate 3673k -maxrate 6822k -bufsize 10496k -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le /media/.tdarr_cache/tdarr-workDir-node-X9sJfpR9J-worker-rare-rail-ts-1724747301261/1724747312923/MyFile.mkv

44

2024-08-27T09:28:37.024Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers

45

2024-08-27T09:28:37.024Z built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)

46

2024-08-27T09:28:37.024Z configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc

47

2024-08-27T09:28:37.024Z libavutil 58. 2.100 / 58. 2.100

48

2024-08-27T09:28:37.024Z libavcodec 60. 3.100 / 60. 3.100

49

2024-08-27T09:28:37.024Z libavformat 60. 3.100 / 60. 3.100

50

2024-08-27T09:28:37.024Z libavdevice 60. 1.100 / 60. 1.100

51

2024-08-27T09:28:37.024Z libavfilter 9. 3.100 / 9. 3.100

52

2024-08-27T09:28:37.024Z libswscale 7. 1.100 / 7. 1.100

53

2024-08-27T09:28:37.024Z libswresample 4. 10.100 / 4. 10.100

54

2024-08-27T09:28:37.024Z libpostproc 57. 1.100 / 57. 1.100

55

2024-08-27T09:28:37.024Z Input #0, matroska,webm, from '/MyPath/MyFile.mkv':

56

2024-08-27T09:28:37.024Z Metadata:

57

2024-08-27T09:28:37.024Z encoder : libebml v1.3.4 + libmatroska v1.4.5

58

2024-08-27T09:28:37.024Z creation_time : 2016-08-16T02:33:43.000000Z

59

2024-08-27T09:28:37.024Z Duration: 00:43:00.37, start: 0.000000, bitrate: 11006 kb/s

60

2024-08-27T09:28:37.024Z Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 19999:20000 DAR 19999:11250], Closed Captions, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)

61

2024-08-27T09:28:37.024Z Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)

62

2024-08-27T09:28:37.024Z Stream #0:2(eng): Subtitle: subrip

63

2024-08-27T09:28:37.024Z Stream mapping:

64

2024-08-27T09:28:37.024Z Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))

65

2024-08-27T09:28:37.024Z Stream #0:1 -> #0:1 (copy)

66

2024-08-27T09:28:37.024Z Stream #0:2 -> #0:2 (copy)

67

2024-08-27T09:28:37.024Z Press [q] to stop, [?] for help

68

2024-08-27T09:28:37.024Z Incompatible pixel format 'p010le' for codec 'libx265', auto-selecting format 'yuv420p10le'

69

2024-08-27T09:28:37.024Z x265 [info]: HEVC encoder version 3.5+1-f0c1022b6

70

2024-08-27T09:28:37.024Z x265 [info]: build info [Linux][GCC 11.2.0][64 bit] 10bit

71

2024-08-27T09:28:37.024Z x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

72

2024-08-27T09:28:37.024Z x265 [info]: Main 10 profile, Level-4 (Main tier)

73

2024-08-27T09:28:37.024Z x265 [info]: Thread pool created using 8 threads

74

2024-08-27T09:28:37.024Z x265 [info]: Slices : 1

75

2024-08-27T09:28:37.024Z x265 [info]: frame threads / pool features : 3 / wpp(17 rows)

76

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

77

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

78

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

79

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

80

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

81

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

82

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

83

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

84

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

85

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

86

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

87

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

88

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

89

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

90

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

91

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

92

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

93

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

94

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

95

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

96

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

97

2024-08-27T09:28:37.024Z set_mempolicy: Operation not permitted

98

2024-08-27T09:28:37.024Z x265 [info]: Coding QT: max CU size, min CU size : 64 / 8

99

2024-08-27T09:28:37.024Z x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra

100

2024-08-27T09:28:37.024Z x265 [info]: ME / range / subpel / merge : hex / 57 / 2 / 3

101

2024-08-27T09:28:37.024Z x265 [info]: Keyframe min / max / scenecut / bias : 23 / 250 / 40 / 5.00

102

2024-08-27T09:28:37.024Z x265 [info]: Lookahead / bframes / badapt : 20 / 4 / 2

103

2024-08-27T09:28:37.024Z x265 [info]: b-pyramid / weightp / weightb : 1 / 1 / 0

104

2024-08-27T09:28:37.024Z x265 [info]: References / ref-limit cu / depth : 3 / off / on

105

2024-08-27T09:28:37.024Z x265 [info]: AQ: mode / str / qg-size / cu-tree : 2 / 1.0 / 32 / 1

106

2024-08-27T09:28:37.024Z x265 [info]: Rate Control / qCompress : ABR-5248 kbps / 0.60

107

2024-08-27T09:28:37.024Z x265 [info]: VBV/HRD buffer / max-rate / init : 10496 / 6822 / 0.750

108

2024-08-27T09:28:37.024Z x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp

109

2024-08-27T09:28:37.024Z x265 [info]: tools: b-intra strong-intra-smoothing lslices=6 deblock sao

110

2024-08-27T09:28:37.024Z Output #0, matroska, to '/media/.tdarr_cache/tdarr-workDir-node-X9sJfpR9J-worker-rare-rail-ts-1724747301261/1724747312923/MyFile.mkv':

111

2024-08-27T09:28:37.024Z Metadata:

112

2024-08-27T09:28:37.024Z encoder : Lavf60.3.100

113

2024-08-27T09:28:37.024Z Stream #0:0: Video: hevc, yuv420p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 5248 kb/s, 23.98 fps, 1k tbn (default)

114

2024-08-27T09:28:37.024Z Metadata:

115

2024-08-27T09:28:37.024Z encoder : Lavc60.3.100 libx265

116

2024-08-27T09:28:37.024Z Side data:

117

2024-08-27T09:28:37.024Z cpb: bitrate max/min/avg: 6822000/0/5248000 buffer size: 10496000 vbv_delay: N/A

118

2024-08-27T09:28:37.024Z Stream #0:1(eng): Audio: eac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), fltp, 640 kb/s (default)

119

2024-08-27T09:28:37.024Z Stream #0:2(eng): Subtitle: subrip

120

2024-08-27T09:28:37.024Z frame= 0 fps=0.0 q=0.0 size= 3kB time=00:00:00.73 bitrate= 36.0kbits/s speed=35.9x frame= 0 fps=0.0 q=21.1 size= 3kB time=00:00:01.79 bitrate= 14.8kbits/s speed=3.11x malloc_consolidate(): invalid chunk size

121

2024-08-27T09:28:37.024Z

122

2024-08-27T09:28:37.024Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:CLI error code: null

123

2024-08-27T09:28:37.024Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Running tdarr-ffmpeg failed

124

2024-08-27T09:28:37.024Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:CLI tdarr-ffmpeg exited with code: null

125

2024-08-27T09:28:37.025Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Error: Running tdarr-ffmpeg failed

126

2024-08-27T09:28:37.025Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:"Running tdarr-ffmpeg failed"

127

2024-08-27T09:28:37.025Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:"Error: Running tdarr-ffmpeg failed\n at /app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:227:27\n at step (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:33:23)\n at Object.next (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:14:53)\n at fulfilled (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/classic/runClassicTranscodePlugin/1.0.0/index.js:5:58)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

128

2024-08-27T09:28:37.025Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:Flow has failed

129

2024-08-27T09:28:37.025Z g2OIuMUT8:Node[MyServer]:Worker[rare-rail]:[-error-]
```

 - OS: Unraid (kernel 6.1.99-Unraid)
 - Running in docker

**Additional context**
As stated a windows node converts the file with no issues. I've restarted and rebooted that server multiple times since and the issue is always there.
Presumably the real error is `malloc_consolidate(): invalid chunk size`, but the server has over 20 gigs of free ram so it's not running out, the file isn't that big.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ulrar** [comment]
Well that's fun, bots triggering each other

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HaveAGitGat** [comment]
Yeah haven’t seen that before, seems GitHub having some trouble with scam bots. Think the accounts were auto deleted.

**Comment by supersnellehenk** [comment]
> Yeah haven’t seen that before, seems GitHub having some trouble with scam bots. Think the accounts were auto deleted.

I reported them :P 
![image](https://github.com/user-attachments/assets/61edb1fc-d7b0-4c9d-9e3f-dc7dc47e07bb)

**Comment by HaveAGitGat** [comment]
Ahh thanks 🙂

**Comment by HaveAGitGat** [comment]
The issue seems related to something locally on your system/config with regards to FFmpeg/libraries/container settings etc. FFmpeg doesn't seem to give an error but you can try running this manually in the container:

` tdarr-ffmpeg -i /MyPath/MyFile.mkv -map 0 -c:v libx265 -b:v 5248k -minrate 3673k -maxrate 6822k -bufsize 10496k -c:a copy -c:s copy -max_muxing_queue_size 9999 -map -0:d -pix_fmt p010le /media/.tdarr_cache/tdarr-workDir-node-X9sJfpR9J-worker-rare-rail-ts-1724747301261/1724747312923/MyFile.mkv`

Perhaps remove some of the arguments and see if that works.

Can also try sample file https://samples.tdarr.io/api/v1/samples/sample__1080__libx264__aac__30s__video.mkv just to double check that works.

**Comment by Ulrar** [comment]
I let my windows node up until it finished processing the whole queue and since then the built in node has been fine.

Presumably the issue was with some specific files in the queue, as it's since processed quite a few new files with no issues.
I don't have the originals and I'm not sure what they were, so there's probably not much more to do here

**Comment by HaveAGitGat** [comment]
Ok thanks for letting me know :)
