### ISSUE TITLE
File scan crashing and stuck in staging when file has large amount of streams

### ISSUE THREAD

**Issue by korewaChino** [HaveAGitGat/Tdarr#1071]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
When reencoding some files, the scan fails and the file gets stuck in staging queue.
```
RangeError: Invalid string length
    at Socket.<anonymous> (/app/Tdarr_Node/srcug/commonModules/fileScanner/runFFprobe.js:1:1828)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[2024-09-02T22:34:04.212] [FATAL] Tdarr_Node - RangeError: Invalid string length
    at Socket.<anonymous> (/app/Tdarr_Node/srcug/commonModules/fileScanner/runFFprobe.js:1:1828)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23){}
```
[NBXS9LY7G-log.txt](https://github.com/user-attachments/files/16839456/NBXS9LY7G-log.txt)

**To Reproduce**
Try to transcode a file

**Expected behavior**
Transcode either fail or pass depending on scan result

 - OS: Linux, K8s
 - Version 2.24.05

**Additional context**

**Comment by HaveAGitGat** [comment]
Do you know how much metadata is in those files? Perhaps a huge a mount of metadata is crashing things.

**Comment by korewaChino** [comment]
I just checked the ffprobe data, yup it's a whole lot of data. I would like to keep all that data whenever possible, can we handle the large data somehow?

**Comment by korewaChino** [comment]
I disabled running MediaInfo and it seemed to start transcoding now...? That's weird.

**Comment by HaveAGitGat** [comment]
Ref: https://discord.com/channels/623392507828371476/1283805900527767574

**Comment by HaveAGitGat** [comment]
Do you have a sample of this file (if it's a public file). I assume it's the `-show_data` ffprobe option which extracts a lot of data.

**Comment by HaveAGitGat** [comment]
Was solved [here](https://discord.com/channels/623392507828371476/1283805900527767574/1285323961206313053) ty.

**Comment by QBANIN** [comment]
> Was solved [here](https://discord.com/channels/623392507828371476/1283805900527767574/1285323961206313053) ty.

I can't open the link (channel loading forever). What's the solution to this issue?
