### ISSUE TITLE
2.25.01 (acc/pre-release) connection issues

### ISSUE THREAD

**Issue by Rwarren873** [HaveAGitGat/Tdarr#1075]
Good morning, I updated from 2.24.01 to 2.25.01 this morning in Unraid's Docker.  I have not been able to get things to work since.  I can't tell if the server is failing to start or if the worker node is failing to connect.  It was working fine prior to the update.

Note the below logs are from the in-built server & node.  I did try to connect with a worker computer but its logs (in essence) say connection refused.

IPs and ports x'd out on purpose.

<p>
<details>
<summary>
Docker Log (repeats every few seconds)
</summary>

```
Starting Tdarr_Server
{
  environment: 'production',
  execDir: '/app/Tdarr_Server',
  appsDir: '/app'
}
[2024-09-06T06:15:23.017] [INFO] Tdarr_Server - Config path: "/app/configs/Tdarr_Server_Config.json"
[2024-09-06T06:15:23.039] [INFO] Tdarr_Server - {
  "serverPort": "xxxx",
  "webUIPort": "xxxx",
  "serverIP": "x.x.x.x",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "platform_arch_isdocker": "linux_x64_docker_true",
  "auth": false,
  "authSecretKey": "*****",
  "maxLogSizeMB": 10
}
[2024-09-06T06:15:23.112] [INFO] Tdarr_Server - Initializing DB
[2024-09-06T06:15:23.156] [ERROR] Tdarr_Node - Failed to contact server, retrying...
[2024-09-06T06:15:25.161] [ERROR] Tdarr_Node - Failed to contact server, retrying...
[2024-09-06T06:15:26.260] [ERROR] Tdarr_Node - Node connection error to: xxx.xxx.xxx.xxx:xxxx
<details><summary>Details</summary>
[2024-09-06T06:15:26.260] [ERROR] Tdarr_Node - Error: xhr poll error
    at Polling.onError (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transport.js:47:37)
    at Request.<anonymous> (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:238:18)
    at Emitter.emit (/app/Tdarr_Node/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:343:14)
    at Timeout._onTimeout (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:316:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7){
  "description": 0,
  "context": {
    "UNSENT": 0,
    "OPENED": 1,
    "HEADERS_RECEIVED": 2,
    "LOADING": 3,
    "DONE": 4,
    "readyState": 4,
    "responseText": "Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)",
    "responseXML": "",
    "status": 0,
    "statusText": {
      "errno": -104,
      "code": "ECONNRESET",
      "syscall": "read"
    }
  },
  "type": "TransportError"
}

```
</details>
</p>

<p>
<details>
<summary>
Server Log (repeats every few seconds)
</summary>

```
}
[2024-09-06T05:39:56.701] [INFO] Tdarr_Server - Initializing DB
[2024-09-06T05:40:02.312] [INFO] Tdarr_Server - version: 2.25.01
[2024-09-06T05:40:02.314] [INFO] Tdarr_Server - platform_arch_isdocker: linux_x64_docker_true
[2024-09-06T05:40:02.315] [INFO] Tdarr_Server - Preparing environment
[2024-09-06T05:40:02.316] [INFO] Tdarr_Server - Tdarr started.
[2024-09-06T05:40:02.316] [INFO] Tdarr_Server - Tdarr documents folder:"/app/server"
[2024-09-06T05:40:02.317] [INFO] Tdarr_Server - Checking directories
[2024-09-06T05:40:03.545] [INFO] Tdarr_Server - Checking binary paths
[2024-09-06T05:40:03.715] [INFO] Tdarr_Server - Running binary tests
[2024-09-06T05:40:06.262] [INFO] Tdarr_Server - Config path: "/app/configs/Tdarr_Server_Config.json"
[2024-09-06T05:40:06.286] [INFO] Tdarr_Server - {
  "serverPort": "xxxx",
  "webUIPort": "xxxx",
  "serverIP": "x.x.x.x",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "platform_arch_isdocker": "linux_x64_docker_true",
  "auth": false,
  "authSecretKey": "*****",
  "maxLogSizeMB": 10
}
[2024-09-06T05:40:06.367] [INFO] Tdarr_Server - Initializing DB

```
</details>
</p>
<p>
<details>
<summary>
Node Log (repeats every few seconds)
</summary>

[2024-09-06T02:31:29.069] [ERROR] Tdarr_Node - Node connection error to: x.x.x.x:xxxx
[2024-09-06T02:31:29.069] [ERROR] Tdarr_Node - Error: xhr poll error
    at Polling.onError (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transport.js:47:37)
    at Request.<anonymous> (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:238:18)
    at Emitter.emit (/app/Tdarr_Node/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:343:14)
    at Timeout._onTimeout (/app/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:316:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7){
  "description": 0,
  "context": {
    "UNSENT": 0,
    "OPENED": 1,
    "HEADERS_RECEIVED": 2,
    "LOADING": 3,
    "DONE": 4,
    "readyState": 4,
    "responseText": "Error: socket hang up\n    at connResetException (node:internal/errors:720:14)\n    at Socket.socketOnEnd (node:_http_client:525:23)\n    at Socket.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "responseXML": "",
    "status": 0,
    "statusText": {
      "code": "ECONNRESET"
    }
  },
  "type": "TransportError"
}

</details>
</p>

**Comment by HaveAGitGat** [comment]
2.25.01 is not out yet, it’s still in acceptance/pre-release stage.

If you’re not meaning to try the pre-release then please use 2.24.05.

You can see the latest here:

https://hub.docker.com/r/haveagitgat/tdarr/tags

https://github.com/HaveAGitGat/Tdarr/pkgs/container/tdarr

**Comment by Rwarren873** [comment]
ok, thank you, i'll give it a try.  I've always used this:

ghcr.io/haveagitgat/tdarr_acc:latest

with no problems and it gave me 2.25.01 this morning.

**Comment by Rwarren873** [comment]
Forcing it back to 2.24.05 did the trick, thank you very much!

ghcr.io/haveagitgat/tdarr_acc:2.24.05

**Comment by HaveAGitGat** [comment]
That’s good but I would not recommend using the _acc images for day to day use as they’re trial/testing acceptance images:

https://en.m.wikipedia.org/wiki/Development,_testing,_acceptance_and_production

**Comment by Rwarren873** [comment]
For some reason GitHub has signed me out and won't let me sign back in...

You're right, I think you had me use the _acc when we were diagnosing an issue months ago and I forgot to change it back.  Thank you again!

**Comment by HaveAGitGat** [comment]
Ah ok no problem. Strange that you had that error though as all the acceptance tests passed and working fine on my machine (been running it for a few days) hmm

**Comment by HaveAGitGat** [comment]
Were those logs from the Tdarr or the unraid container? You'd need to check the unraid container logs as if something external is causing Tdarr server to crash then it won't show up in the Tdarr logs but will show up in the unraid container logs.

**Comment by Rwarren873** [comment]
The one labeled Docker Log is from the container logs, it's the one that appears to have a db initialization issue or maybe a node <> server issue which makes no sense because they are in the same container.  Like I said, I did attempt startup on a "worker" machine (Win11) and the node refused to start up with very similar errors.  It presents as a failure to connect or transport error (see below).

Note that again, I did nothing other than allow the container to update in Unraid.  I do have worker computers configured to update from the server, which also appears to have failed.
<p>
<Details>
<summary>
From the worker computer:
</summary>

```
[2024-09-06T06:12:11.808] [INFO] Tdarr_Node - Config validation passed
[2024-09-06T06:12:16.338] [INFO] Tdarr_Node - version: 2.23.01
[2024-09-06T06:12:16.338] [INFO] Tdarr_Node - platform_arch_isdocker: win32_x64_docker_false
[2024-09-06T06:12:16.339] [INFO] Tdarr_Node - Starting Tdarr_Node
[2024-09-06T06:12:16.339] [INFO] Tdarr_Node - Preparing environment
[2024-09-06T06:12:16.340] [INFO] Tdarr_Node - Path translator: Checking Node path: //x.x.x.x/
[2024-09-06T06:12:16.368] [INFO] Tdarr_Node - Running binary tests
[2024-09-06T06:12:16.428] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: //x.x.x.x/serverpath
[2024-09-06T06:12:16.428] [INFO] Tdarr_Node - Path translator: Checking Node path: //x.x.x.x/serverpath
[2024-09-06T06:12:16.433] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: //x.x.x.x/serverpath
[2024-09-06T06:12:16.434] [INFO] Tdarr_Node - Path translator: Checking Node path: //x.x.x.x/serverpath
[2024-09-06T06:12:16.438] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: //x.x.x.x/serverpath
[2024-09-06T06:12:16.439] [INFO] Tdarr_Node - Path translator: Checking Node path: //x.x.x.x/serverpath
[2024-09-06T06:12:16.443] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: //x.x.x.x/serverpath
[2024-09-06T06:12:16.969] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2024-09-06T06:12:16.969] [INFO] Tdarr_Node - handbrakePath:"C:/xxxx/Tdarr/Tdarr_Node/assets/app/HandBrakeCLI.exe"
[2024-09-06T06:12:16.969] [INFO] Tdarr_Node - ffmpegPath:"C:/xxxx/Tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg.exe"
[2024-09-06T06:12:16.969] [INFO] Tdarr_Node - mkvpropedit:"C:/xxxx/Tdarr/Tdarr_Node/assets/app/mkvpropedit/windows/mkvpropedit.exe"
[2024-09-06T06:12:16.969] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - Binary test 3: mkvpropeditPath working
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - Running scanner tests
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - ---------------Scanner tests start----------------
[2024-09-06T06:12:16.970] [INFO] Tdarr_Node - ffprobePath:"C:/xxxx/Tdarr/Tdarr_Node/node_modules/@ffprobe-installer/win32-x64/ffprobe.exe"
[2024-09-06T06:12:16.971] [INFO] Tdarr_Node - ccextractorPath:"C:/xxxx/Tdarr/Tdarr_Node/assets/app/ccextractor/ccextractorwin.exe"
[2024-09-06T06:12:16.971] [INFO] Tdarr_Node - Scanner test: Scanning file start
[2024-09-06T06:12:18.402] [ERROR] Tdarr_Node - Node connection error to: x.x.x.x:xxxx
[2024-09-06T06:12:18.403] [ERROR] Tdarr_Node - Error: xhr poll error
    at Polling.onError (C:\xxxx\Tdarr\Tdarr_Node\node_modules\engine.io-client\build\cjs\transport.js:47:37)
    at Request.<anonymous> (C:\xxxx\Tdarr\Tdarr_Node\node_modules\engine.io-client\build\cjs\transports\polling.js:238:18)
    at Emitter.emit (C:\xxxx\Tdarr\Tdarr_Node\node_modules\@socket.io\component-emitter\index.js:143:20)
    at Request.onError (C:\xxxx\Tdarr\Tdarr_Node\node_modules\engine.io-client\build\cjs\transports\polling.js:343:14)
    at Timeout._onTimeout (C:\xxxx\Tdarr\Tdarr_Node\node_modules\engine.io-client\build\cjs\transports\polling.js:316:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7){
  "description": 0,
  "context": {
    "UNSENT": 0,
    "OPENED": 1,
    "HEADERS_RECEIVED": 2,
    "LOADING": 3,
    "DONE": 4,
    "readyState": 4,
    "responseText": "Error: connect ECONNREFUSED x.x.x.x:xxxx\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)",
    "responseXML": "",
    "status": 0,
    "statusText": {
      "errno": -4078,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "x.x.x.x",
      "port": xxxx
    }
  },
  "type": "TransportError"
}

```
</details></p>

**Comment by HaveAGitGat** [comment]
The node has that connection error because the server isn’t up and running yet so I’m wondering if there’s any more in the Docker server log where it mentions why the server is crashing.

**Comment by Rwarren873** [comment]
I see nothing in the docker logs for that time frame that looks suspicious.  I'll try recreating it after work today and see what I can find out.

**Comment by HaveAGitGat** [comment]
Ok thanks would really appreciate it.

**Comment by Rwarren873** [comment]
I don't see any differences in the logs when I recreated it vs the ones in my OP.  The only thing I haven't tried is removing the container completely and starting over, which I'd rather not do.  I finally have flows working the way I want and don't want to lose all that work.

I'd love to help, I just don't know what else I can do on this side.  Is there an enhanced logging toggle that I don't see maybe?

**Comment by HaveAGitGat** [comment]
Are you able to share the server log from the container logs?

For the node connection IP are you using `0.0.0.0`, `localhost`, `127.0.01` or the specific machine IP?

From the server log you posted before, it seems the server isn't up and running so I don't think it's normal (unless your force restarted the server container here):

```
[2024-09-06T05:39:56.701] [INFO] Tdarr_Server - Initializing DB
...
[2024-09-06T05:40:03.715] [INFO] Tdarr_Server - Running binary tests
...
crash
...
starting up again
[2024-09-06T05:40:06.262] [INFO] Tdarr_Server - Config path: "/app/configs/Tdarr_Server_Config.json"
[2024-09-06T05:40:06.367] [INFO] Tdarr_Server - Initializing DB
```

**Comment by HaveAGitGat** [comment]
@Rwarren873 are you able to repull `ghcr.io/haveagitgat/tdarr_acc:latest` and see if that now works for you? If it's similar to a network issue that another person was having then it should now be resolved, thanks.

**Comment by Rwarren873** [comment]
I use the IP for the server with the port.  Like 10.10.10.10:8888  Even though the node & server are in the same container it never occurred to me to do it either of the ways you asked about.

the acc:latest did indeed resolve it.  I'm up and running with 2.25.01 now.

**Comment by HaveAGitGat** [comment]
Great thank you :)
