### ISSUE TITLE
Problem with using docker node in linux with folder names with spaces.

### ISSUE THREAD

**Issue by haakony** [HaveAGitGat/Tdarr#1135]
**Is your feature request related to a problem? Please describe.**
Problem with using docker node in linux with folder names with spaces.
Edit: Under NFS share

**Describe the solution you'd like**
A option to add backslash on spaces, as i could not find any.

**Additional context**

```
[2024-12-20T08:42:46.678] [WARN] Tdarr_Node - FFprobe was unable to extract any data from this file: "/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv" as the FFprobe result is {}
[2024-12-20T08:42:46.987] [ERROR] Tdarr_Node - {
  "result": "error",
  "error": {}
}
[2024-12-20T08:42:47.071] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, open '/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv'{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv"
}
[2024-12-20T08:42:47.073] [ERROR] Tdarr_Node - Error running MediaInfo 3
[2024-12-20T08:42:47.073] [ERROR] Tdarr_Node - ENOENT: no such file or directory, open '/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv'
[2024-12-20T08:42:47.075] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, access '/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv'
    at Object.accessSync (node:fs:254:3)
    at c (/app/Tdarr_Node/srcug/workers/worker1.js:1:27644)
    at preProcessFile (/app/Tdarr_Node/srcug/workers/worker1.js:1:28488){
  "errno": -2,
  "syscall": "access",
  "code": "ENOENT",
  "path": "/media/Movies/Some Movie (2024)/Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv"
}

```
To access the NFS share with spaces in folder name you need to add slashes to escape them

```
root@3abda143b59b:/# ls /media/Movies/Some\ Movie\ \(2024\)/
Some.Movie.2024.MULTi.1080p.WEB.H264-LOST.mkv
```

**Comment by supersnellehenk** [comment]
Tdarr runs its commands in such a way that it doesn't need escaping of spaces, this is most likely a path/permission issue.

**Comment by haakony** [comment]
suddenly getting new error
