### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by mattman73** [HaveAGitGat/Tdarr#121]
**Describe the bug**
After running the startup command line.
This is the error I'm getting.
MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost/ node main.js
/home/admin/Tdarr/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/admin/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/admin/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/admin/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**To Reproduce**
every time I run the startup command line.

**Expected behavior**
I would have liked the software to install and the run.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 27

**Comment by zmiguel** [comment]
is your mongodb server running?

**Comment by HaveAGitGat** [comment]
@mattman73 yes it looks as if MongoDB Server is not running. Perhaps take a look at this:

https://tecadmin.net/install-mongodb-on-fedora/

**Comment by HaveAGitGat** [comment]
Let me know if you still have issues.
