### ISSUE TITLE
Fiber.node is missing

### ISSUE THREAD

**Issue by zmiguel** [HaveAGitGat/Tdarr#123]
**Describe the bug**
fiber.node module missing from linux 7z file

**To Reproduce**

- extract linux release
- cd to extracted folder
- start Tdarr with command: ` MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost/ node bundle/main.js`

**Expected behavior**
Tdarr should start successfully 

**Screenshots**
```
## There is an issue with `node-fibers` ##
`/opt/Tdarr/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers.node` is missing.

Try running this to fix the issue: /usr/bin/node /opt/Tdarr/bundle/programs/server/node_modules/fibers/build
Error: Cannot find module '/opt/Tdarr/bundle/programs/server/node_modules/fibers/bin/linux-x64-72-glibc/fibers'
Require stack:
- /opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js
- /opt/Tdarr/bundle/programs/server/boot.js
- /opt/Tdarr/bundle/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/boot.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: none
 - Version: Beta v1.101

**Additional context**
I've tried the recommended command `/usr/bin/node /opt/Tdarr/bundle/programs/server/node_modules/fibers/build` and I get the error: `gyp: binding.gyp not found (cwd: /opt/Tdarr) while trying to load binding.gyp`

**Comment by zmiguel** [comment]
Seems to be related to using node 12 and this requiring node 8.

Please update this to support a currently active LTS release of node.

Thanks.

**Comment by zmiguel** [comment]
Changing `programs/server/package.json` file:

`"fibers": "4.0.2"` fixed the issue

**Comment by agneevX** [comment]
Still facing the issue with correct version of node...

_Raspberry Pi 4B (4GB) running Raspbian Buster_
```text
agneev@pi4:/opt/Tdarr/bundle $ MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost/ /home/agneev/.nvm/versions/node/v8.16.1/bin/node --max_old_space_size=8152 main.js
## There is an issue with `node-fibers` ##
`/opt/Tdarr/bundle/programs/server/node_modules/fibers/bin/linux-arm-57-glibc/fibers.node` is missing.

Try running this to fix the issue: /home/agneev/.nvm/versions/node/v8.16.1/bin/node /opt/Tdarr/bundle/programs/server/node_modules/fibers/build
Error: Cannot find module '/opt/Tdarr/bundle/programs/server/node_modules/fibers/bin/linux-arm-57-glibc/fibers'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Tdarr/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:653:30)
```
