### ISSUE TITLE
iso-639-2 module missing

### ISSUE THREAD

**Issue by bassrock** [HaveAGitGat/Tdarr#135]
**Describe the bug**
I currently use the ubuntu aio docker image. Contstantly in the logs I see an error where the iso-639-2 module is missing.

**To Reproduce**
Not sure what causes it to happen.

**Expected behavior**
The log does not show up.

**Screenshots**
Stack trace:

```
Error: Cannot find module '/home/Tdarr/Documents/node_modules/iso-639-2'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/plugins/Community/Tdarr_Plugin_e5c3_CnT_Add_Subtitles.js:2:17)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at module.exports.moduleId (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/import-fresh/index.js:31:32)
at fs.readdirSync.forEach.file (server/main.js:1004:20)
at Array.forEach (<anonymous>)
at MethodInvocation.searchPlugins (server/main.js:990:65)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at Promise (packages/ddp-server/livedata_server.js:715:46)
```

**Desktop (please complete the following information):**
 - Docker, unRaid

**Comment by HaveAGitGat** [comment]
Hi, it’s due to this community plugin:

https://github.com/HaveAGitGat/Tdarr_Plugins/blob/master/Community/Tdarr_Plugin_e5c3_CnT_Add_Subtitles.js

Need to come up with a solution for when community plugins use extra modules.

**Comment by bassrock** [comment]
Oh ok. Interesting. Something to note too is I am not even using this one. I'm guessing tdarr then loads all of them when you search?

**Comment by HaveAGitGat** [comment]
Yeah that’s right. They’re all imported every time a plugin search is done. An auto-search is done every time you visit the Plugins tab to load all the plugins.

https://github.com/HaveAGitGat/Tdarr/blob/45ef24d9c3c4005eb8f941723be1bfed5fc34398/server/main.js#L1004

**Comment by HaveAGitGat** [comment]
I've updated the plugin so the error isn't thrown and the plugin instructions are shown when browsing community plugins:
![image](https://user-images.githubusercontent.com/43864057/73602765-abd8fe80-4570-11ea-88d9-826a3ba0cbdd.png)
