### ISSUE TITLE
Docker tool should recommend --network="bridge" for AIO

### ISSUE THREAD

**Issue by Webreaper** [HaveAGitGat/Tdarr#212]
I installed Tdarr AIO using the docker command recommended by the tool on the site. However, it failed to start with a Mongo connection error: 

`failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
`

After asking on [reddit](https://www.reddit.com/r/Tdarr/comments/ggyz8s/mongodb_connection_failure_using_aio/) somebody suggested that using a bridge would solve it, so I tried adding `--network="bridge"` and it started up just fine.

Might be worth suggesting that either in the readme, faq, or the docker command generator.

**Comment by HaveAGitGat** [comment]
Ok thanks I’ll add this in

**Comment by cmartin616** [comment]
I also have this error whether or not the container is in the bridge network:

`MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
    at Pool.<anonymous> (/app/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:198:13)
    at Pool.EventEmitter.emit (domain.js:448:20)
    at Connection.<anonymous> (/app/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at Socket.<anonymous> (/app/Tdarr/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

Docker config:

`docker create \
  --name=tdarr \
  --restart=always \
  -e PGID=971 \
  -e PUID=1034 \
  -e TZ=America/New_York \
  -p 8265:8265 \
  -v TdarrData:/var/lib/mongodb/ \
  -v /[mymediadrive]/movies:/home/Tdarr/Media/movies \
  -v /[mymediadrive]/tv:/home/Tdarr/Media/tv \
  haveagitgat/tdarr:1.108`

Portainer lists these parameters:

`
PGID | 971
PUID | 1034
TZ | America/New_York
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MONGO_URL | mongodb://mongodb:27017/tdarr
PORT | 8265
ROOT_URL | http://0.0.0.0/
NODE_ARGS | --max-old-space-size=16384
HOME | /home/Tdarr
`

Any help would be appreciated because I'd love to give your application a spin!

**Comment by HaveAGitGat** [comment]
@Webreaper  added that in

@cmartin616 Please try the new 'tdarr' container in an hour or so
