### ISSUE TITLE
Missing Binary

### ISSUE THREAD

**Issue by Deltron216** [HaveAGitGat/Tdarr#242]
installing on Windows 10 (no Docker) getting the following error

D:\Tdarr-Windows-1.1092\Tdarr-Windows-01-pre-alpha1\bundle\programs\server\node_modules\fibers\fibers.js:23

throw new Error('Missing binary. See message above.');

^

Error: Missing binary. See message above.

at Object.<anonymous> (D:\Tdarr-Windows-1.1092\Tdarr-Windows-01-pre-alpha1\bundle\programs\server\node_modules\fibers\fibers.js:23:9)

at Module._compile (internal/modules/cjs/loader.js:1138:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

at Module.load (internal/modules/cjs/loader.js:986:32)

at Function.Module._load (internal/modules/cjs/loader.js:879:14)

at Module.require (internal/modules/cjs/loader.js:1026:19)

at require (internal/modules/cjs/helpers.js:72:18)

at Object.<anonymous> (D:\Tdarr-Windows-1.1092\Tdarr-Windows-01-pre-alpha1\bundle\programs\server\boot.js:1:13)

at Module._compile (internal/modules/cjs/loader.js:1138:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

Any ideas as to how to resolve this?

**Comment by redfellow** [comment]
I had the same issue, installing the missing module failed, so did an attempt of npm install (according to README file).

After one hour of messing around, I can conclude that this is not easily fixable by the end user, without more info or a fixed release from the maintainers.

Tested both the latest stable and alpha.

**Comment by HaveAGitGat** [comment]
This is normally an issue to do with using the incorrect version of NodeJS. Make sure to use 8.16.1. Use node version manager for windows if needed.
https://github.com/coreybutler/nvm-windows

**Comment by redfellow** [comment]
I'll try again with 8.16.1, I think I might be mistakenly running 12.x.x

**Comment by HaveAGitGat** [comment]
Ok, feel free to re-open if you still have the issue.
