### ISSUE TITLE
Heart character (♥) causes scan to fail

### ISSUE THREAD

**Issue by kenvalleydc** [HaveAGitGat/Tdarr#254]
It took me a while to figure this out, but using the heart character in a path (as in I ♥ Huckabees) caused the Scan (Fresh) to stop when it hit that title.  My be other non-ASCII characters, too, but that was the one I ran into.

**Comment by kenvalleydc** [comment]
Also found WALL·E causes issue:
[2020-07-31T13:02:05.600] [ERROR] tdarr - Scanner WHr4FmUVI:Error: ENOENT: no such file or directory, lstat '/home/Tdarr/media/Multimedia/Movies/WALL�E (2008)'
    at Object.fs.lstatSync (fs.js:941:11)
    at fs.readdirSync.forEach (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/fileScanner/fileScanner.js:121:18)
    at Array.forEach (<anonymous>)
    at traverseDir (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/fileScanner/fileScanner.js:117:37)
    at Object.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/assets/app/fileScanner/fileScanner.js:114:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by kenvalleydc** [comment]
Long dash, too: Foo Fighters – Landmarks Live in Concert

**Comment by kenvalleydc** [comment]
Perhaps could use this to convert ISO to UTF-8: https://github.com/bnoordhuis/node-iconv

**Comment by jeff47** [comment]
Here's a possible fix, if you use Docker and are familiar with dockerfile:  https://github.com/HaveAGitGat/Tdarr/issues/263

**Comment by HaveAGitGat** [comment]
This should be working on v2, please reopen if needed:

![image](https://user-images.githubusercontent.com/43864057/105867909-e2b3ea00-5ff5-11eb-8128-4995a47719ff.png)

v2 instructions here:
http://tdarr.io/docs/
