### ISSUE TITLE
Some tweaks to better accomodate Linux packaging standards

### ISSUE THREAD

**Issue by Nocifer** [HaveAGitGat/Tdarr#298]
**Is your feature request related to a problem? Please describe.**
I'm trying to package Tdarr for Arch Linux and I'm experiencing some issues.

**Describe alternatives you've considered**
I could do it myself during the packaging process, but I'd prefer if these changes were implemented upstream.

**Additional context**
1. The latest upstream NodeJS version is 15, so the bundled binaries for module 'fibers' fail to run (something I've found is the reason behind a number of previously reported issues). Unless versions of NodeJS older than 12 create known issues and are officially unsupported, it would be best to either provide 'fibers' binaries for all currently maintained Node versions, up to and including the latest one, or at least specifically mention the need to build them when using a more current NodeJS version.
2. The Linux prebuilt release zip contains some Windows executables (ccextractorwin.exe, mkvpropedit.exe, HandBrakeCLI.exe) that are both unnecessary and space-consuming.
3. My next two points were going to be about a) the option to use a system-wide FFmpeg binary, and b) the possibility to specify a different data directory than %user%/Documents/Tdarr; but upon further investigation (namely, checking the Docker & Windows sections of the [installation guide](https://tdarr.io/docs/) at the last minute before posting this) I learned that there are indeed environment variables provided for exactly these two options (DATA & FFmpegPath, respectively). These should definitely be also mentioned in the Linux section of the guide, where they would be most useful.
4. Opting to create a writable 'plugins' folder inside Tdarr's install directory during runtime is liable to produce permission issues if Tdarr is running as anything other than the user which performed the install, because that directory will only be writable by that specific user. E.g, when Tdarr is installed as root via a package manager and then started as non-root:
```
[2020-11-14T15:39:12.659] [INFO] tdarr - Updating plugins
[2020-11-14T15:39:12.739] [INFO] tdarr - Cloning plugins
[2020-11-14T15:39:12.751] [INFO] tdarr - Exit code: 0
[2020-11-14T15:39:12.753] [INFO] tdarr - Queue builder launched
[2020-11-14T15:39:12.764] [INFO] tdarr - [0.01s] Queue builder finished. 0 files processed
[2020-11-14T15:39:13.986] [INFO] tdarr - Finished downloading plugins!
[2020-11-14T15:39:16.158] [ERROR] tdarr - Error: EACCES: permission denied, mkdir '/usr/lib/tdarr/programs/server/assets/app/plugins'
    at Object.mkdirSync (node:fs:1002:3)
    at mkdirsSync (/usr/lib/tdarr/programs/server/npm/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at handleFilterAndCopy (/usr/lib/tdarr/programs/server/npm/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:35)
    at Object.copySync (/usr/lib/tdarr/programs/server/npm/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at server/pluginFuncs.js:210:33
    at /usr/lib/tdarr/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
[2020-11-14T15:39:16.163] [INFO] tdarr - [3.503s]Plugin update finished
```
This 'plugins' folder should probably either be created and populated during setup if its contents are supposed to be static, or created in the data dir (i.e. %user/Documents/Tdarr by default) if its contents are supposed to be volatile.

That's all, thanks for reading this.

**Comment by HaveAGitGat** [comment]
All of those points have been addressed in V2. Thanks.
