### ISSUE TITLE
Updated instructions for Linux?

### ISSUE THREAD

**Issue by wsegatto** [HaveAGitGat/Tdarr#312]
**Describe the bug**
The general instructions and the instructions for Debian do not work. I can't seem to run the application.

**To Reproduce**
Follow the general and specific steps for Debian Buster.
node -v = v12.20.1
gcc -v = 6.14.11

**Screenshots**
Tried installing Node 8 but the issue is the same with the latest Node/npm.

When running, the following error occurs:

```
pi@raspberrypi:/opt/Tdarr-Linux-1.2070/bundle $ /usr/bin/node /opt/Tdarr-Linux-1.2070/bundle/main.js
## There is an issue with `node-fibers` ##
`/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers.node` is missing.

Try running this to fix the issue: /usr/bin/node /opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build
Error: Cannot find module '/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers'
Require stack:
- /opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/fibers.js
- /opt/Tdarr-Linux-1.2070/bundle/programs/server/boot.js
- /opt/Tdarr-Linux-1.2070/bundle/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.Mp._compile (/opt/Tdarr-Linux-1.2070/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Module.Mp.load (/opt/Tdarr-Linux-1.2070/bundle/programs/server/runtime.js:15:31)
/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.Mp._compile (/opt/Tdarr-Linux-1.2070/bundle/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Module.Mp.load (/opt/Tdarr-Linux-1.2070/bundle/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Tdarr-Linux-1.2070/bundle/programs/server/boot.js:2:15)
```

The error says:

`Try running this to fix the issue: /usr/bin/node /opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build`

Well:

```
pi@raspberrypi:/opt/Tdarr-Linux-1.2070/bundle $ sudo /usr/bin/node /opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@12.20.1 | linux | arm64
gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/Tdarr-Linux-1.2070/bundle/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/12.20.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.20.1',
gyp info spawn args   '-Dnode_gyp_dir=/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.20.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/Tdarr-Linux-1.2070/bundle',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /opt/Tdarr-Linux-1.2070/bundle) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.79-v8+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /opt/Tdarr-Linux-1.2070/bundle
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
```

I have gcc-c++, python, make and g++ installed.

It simply doesn't work. Any ideas?

**Comment by wsegatto** [comment]
Does it even work on arm architectures? 32? 64?

**Comment by KenwoodFox** [comment]
Does tdarr work on BSD? I don't have any Linux hosts in my media server environment.

**Comment by 3n8** [comment]
> Does it even work on arm architectures? 32? 64?

idk if V1 works on arm but v2 does but it is not officially released for another 12 dayes: https://github.com/HaveAGitGat/Tdarr/tree/master/updater

If you want support the discord is quite active: https://discord.gg/GF8X8cq

**Comment by wsegatto** [comment]
I was able to solve the "fibers" issue by doing exactly the following:

a) Navigate to `bundle/programs/server/node_modules/fibers`.
b) Run `sudo /usr/bin/node /home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build`.

Results should look like this:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | arm64
gyp info find Python using Python version 3.8.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
../src/fibers.cc:355:59: warning: cast between incompatible function types from ‘uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&)’} to ‘v8::AccessorNameGetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’} [-Wcast-function-type]
  355 |   object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/fibers.cc:355:95: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)’ {aka ‘void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} to ‘v8::AccessorNameSetterCallback’ {aka ‘void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)’} [-Wcast-function-type]
  355 | CurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter).ToChecked();
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
../src/fibers.cc: At global scope:
/usr/include/nodejs/src/node.h:608:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  608 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/src/node.h:642:3: note: in expansion of macro ‘NODE_MODULE_X’
  642 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/fibers.cc:930:1: note: in expansion of macro ‘NODE_MODULE’
  930 | NODE_MODULE(fibers, init)
      | ^~~~~~~~~~~
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/build'
gyp info ok
Installed in `/home/will/tmp/Tdarr-Linux-1.2070/bundle/programs/server/node_modules/fibers/bin/linux-arm64-72-glibc/fibers.node`
```

**Comment by wsegatto** [comment]
I'm closing this since V2 is coming soon. This one seems broken.
