### ISSUE TITLE
Windows Node and Server error

### ISSUE THREAD

**Issue by soultaco83** [HaveAGitGat/Tdarr#316]
**Describe the bug**
Updated the window's version to 1.99.12 and now receiving the below error anytime a video is attempted to transcode on the windows node via the docker server from H264 to HEVC. 

```
Error: Cannot find module 'npm'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at throwNotFoundError (D:\snapshot\tdarr_express_node\node_modules\global-npm\index.js:11:13)
    at Object.<anonymous> (D:\snapshot\tdarr_express_node\node_modules\global-npm\index.js:19:3)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\snapshot\tdarr_express_node\node_modules\npmi\npmi.js:1:76)
[2021-01-19T05:57:38.907] [FATAL] Tdarr_Node - Error: Cannot find module 'npm'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at throwNotFoundError (D:\snapshot\tdarr_express_node\node_modules\global-npm\index.js:11:13)
    at Object.<anonymous> (D:\snapshot\tdarr_express_node\node_modules\global-npm\index.js:19:3)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\snapshot\tdarr_express_node\node_modules\npmi\npmi.js:1:76)
```

When I attempt to run the windows server 1.99.12 I get the following: 
undefined
```
Preparing environment
C:/Users/Games/Desktop/tdarr_11/configs/Tdarr_Server_Config.json
{ serverPort: '8266', handbrakePath: '', ffmpegPath: '' }
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:SettingsGlobalJSONDB
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):2:LibrarySettingsJSONDB
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):4:NodeJSONDB
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:StatisticsJSONDB
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:StagedJSONDB

[2021-01-19T06:04:17.159] [WARN] Tdarr_Server - Not running inside a Docker container
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: Cannot find module 'npm'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at throwNotFoundError (D:\snapshot\tdarr_express_be\node_modules\global-npm\index.js:11:13)
    at Object.<anonymous> (D:\snapshot\tdarr_express_be\node_modules\global-npm\index.js:19:3)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\snapshot\tdarr_express_be\node_modules\npmi\npmi.js:1:76)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31) {
  code: 'MODULE_NOT_FOUND',
  pkg: true
}
```

**To Reproduce**
Open the windows node and either linux/docker server. Attempt to transcode a file. 
For the server error: Just attempt to run

**Comment by soultaco83** [comment]
resolved with new update pushed earlier in morning. Message from HGG: 
"sorry about that, seems one of the dependencies wanted the host machine to have npm installed on it. Didn't catch that error as all my machines have npm on. I've updated the packages so you should no longer get that error"
