### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '/mnt/transcode_cache/filename.mkv'

### ISSUE THREAD

**Issue by marshalleq** [HaveAGitGat/Tdarr#359]
**Describe the bug**
Transcoded file does not copy to source.  This occurs both on remote node and local node.

**To Reproduce**
Encode a file, look at the error log in the staging area.

**Expected behavior**
File would be copied to source, instead it is left in the cache.  Have tried moving cache folder to /temp/ as per one of your suggestions.

The extremely messy unraid docker templates aren't helping the confusion, with multiple unnecessary fields in them, duplicate fields etc, but I understand that is outside of you control.  So I've been manually aligning them to the documentation example at https://tdarr.io/docs/

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Safari / Firefor
 - Version 2.0.0.03

**Additional context**
I'm using the latest tag - not sure if that's what I'm meant to be using

**Comment by marshalleq** [comment]
Solved, I hadn't realised the same directory was needed for the cache as in the exact same location, not just the same path like it would be for some other apps.  Docs are a bit ambiguous - I'd suggest removing the word path and replace with location.

**Comment by tyhawk** [comment]
I ran into the same issue at first.
I think the best way to improve the documentation is to clearly state that the cache directory needs to be shared between the server and nodes as the server doesn't only hand out work to the node, but also handles the copying from the cache to the destination directory.

**Comment by HaveAGitGat** [comment]
Updated to :

`Make sure the Node and Server machines have the same media library and transcode cache locations. In other words, the cache and library must be shared between the Node and Server.`

**Comment by killo3967** [comment]
I have the same problem. 

My configuration in the server (Windows 10) is 
library -> T:
transcode cache -> D:\TDARR_transcodecache

Localy in the server all works perfect, but no in othe windows node.
In the remote node I map the units

net use t: \\server\t$
net use d: \\server\d$

So the local and the remotes units are the same.

I also confirm the read/write access from the remote node to the server units D: and T:

In the remote node, the node configuration file i only modify the ip address and do not made any translation.

But the result is:
 [2023-01-14T22:45:59.902] [INFO] Tdarr_Node - version: 2.00.18
[2023-01-14T22:45:59.903] [INFO] Tdarr_Node - win32_x64_docker_false
[2023-01-14T22:45:59.904] [INFO] Tdarr_Node - Starting Tdarr_Node
[2023-01-14T22:45:59.904] [INFO] Tdarr_Node - Preparing environment
[2023-01-14T22:45:59.906] [INFO] Tdarr_Node - Updating plugins
[2023-01-14T22:45:59.974] [INFO] Tdarr_Node - Node connected & registered
[2023-01-14T22:46:00.569] [INFO] Tdarr_Node - Cloning plugins
[2023-01-14T22:46:00.734] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-01-14T22:46:00.734] [INFO] Tdarr_Node - handbrakePath:C:/Tdarr/Tdarr_Node/assets/app/HandBrakeCLI.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - ffmpegPath:C:/Tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - mkvpropedit:C:/Tdarr/Tdarr_Node/assets/app/mkvpropedit/windows/mkvpropedit.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-01-14T22:46:01.330] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-14T22:46:05.475] [INFO] Tdarr_Node - [4909]Plugin update finished
[2023-01-14T22:46:05.713] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, access 'T:/Érase una vez (2011)/Érase una vez - 4x01 - El cuento de las dos hermanas.avi'
    at Object.accessSync (fs.js:228:3)
    at Object.accessSync (pkg/prelude/bootstrap.js:1474:34)
    at _0x274ea4 (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:49056)
    at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:49485
    at _0x2c23c7 (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:10643)
    at Object.next (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8962)
    at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8430
    at new Promise (<anonymous>)
    at __awaiter (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:7746)
    at preProcessFile (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:48510) {
  errno: -4058,
  syscall: 'access',
  code: 'ENOENT',
  path: 'T:/Érase una vez (2011)/Érase una vez - 4x01 - El cuento de las dos hermanas.avi'
}

Of course, i am doing something wrong, but what?
