### ISSUE TITLE
tdarr_server.exe crashes often

### ISSUE THREAD

**Issue by DankMemeGuy** [HaveAGitGat/Tdarr#412]
**Describe the bug**
The Node and WebUI will remain functioning, but Server crashes. I'm not sure where to obtain the log from. Not sure why this is happening, or how to reproduce. I'm on Windows 10 Pro. This issue happens once a day, maybe twice.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

**Comment by HaveAGitGat** [comment]
Closing this as I think it is related to this one:
https://github.com/HaveAGitGat/Tdarr/issues/412

**Comment by DankMemeGuy** [comment]
@HaveAGitGat Which issue?

**Comment by HaveAGitGat** [comment]
> @HaveAGitGat Which issue?


The one I linked:
https://github.com/HaveAGitGat/Tdarr/issues/412

**Comment by DankMemeGuy** [comment]
> > @HaveAGitGat Which issue?
> 
> The one I linked:
> #412

That issue is this issue? Look at the URL

**Comment by HaveAGitGat** [comment]
You might be right. I meant this one:
https://github.com/HaveAGitGat/Tdarr/issues/386

**Comment by DankMemeGuy** [comment]
> You might be right. I meant this one:
> #386

Yeah I think so. I have been using 2.0.09 and so far it's running like butter compared to the 07 version. I'll let it run a few days but I think this fixed the weird server crashing bug.

**Comment by DankMemeGuy** [comment]
@HaveAGitGat update: it's still crashing. This is the last message in the server log. https://pastebin.com/SzUytP9m

**Comment by HaveAGitGat** [comment]
That’s a different error. It may be due to this bug which has been fixed:

https://github.com/HaveAGitGat/Tdarr/issues/423

Redownload 09 and hopefully that sorts it out for you. 

Keep an eye on the memory graphs on the ‘Stats’ tab near the bottom.

Been running well on my Pi for 24 hours or so, pleased to hear it’s much smoother 😁.

**Comment by DankMemeGuy** [comment]
Ah, I'm redownloading 09, and got this error for the node:
            
            [2021-04-07T05:09:15.722] [INFO] Tdarr_Updater - Tdarr_Updater | v2.00.08
            [2021-04-07T05:09:15.723] [INFO] Tdarr_Updater - Tdarr_Updater | Required platform_arch:win32_x64
            [2021-04-07T05:09:15.724] [INFO] Tdarr_Updater -
            [2021-04-07T05:09:15.725] [INFO] Tdarr_Updater -
            
            **[2021-04-07T05:09:15.725] [INFO] Tdarr_Updater - Tdarr_Node | Current version: 2.00.08 | Required version: 2.00.09
            [2021-04-07T05:09:15.725] [WARN] Tdarr_Updater - Tdarr_Node | Not the required version! Updating to version: 2.00.09!
            Downloading 0.00 KB/s:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%)
            [2021-04-07T05:10:51.069] [INFO] Tdarr_Updater - Tdarr_Node | Downloaded!
            [2021-04-07T05:10:51.069] [INFO] Tdarr_Updater - Tdarr_Node | Unzipping!**
            
            [2021-04-07T05:10:51.632] [ERROR] Tdarr_Updater - Tdarr_Node | Error: unexpected end of file
            [2021-04-07T05:10:51.633] [ERROR] Tdarr_Updater - Tdarr_Node | Error unzipping!
            [2021-04-07T05:10:51.635] [INFO] Tdarr_Updater -
            [2021-04-07T05:10:51.635] [INFO] Tdarr_Updater -
            [2021-04-07T05:10:51.636] [INFO] Tdarr_Updater - Tdarr_Server | Current version: 2.00.08 | Required version: 2.00.09
            Downloading 1664.80 KB/s:>>>>>>>>>>>>>>>>>>>_______________________________(39%)


And the node application doesnt open

**Comment by jaycedk** [comment]
Just tried this.
If you go to the folde .Staging you will finde the zip file.
Unpack that into the Tdarr_Node dir and you can run it.

**Comment by HaveAGitGat** [comment]
`Tdarr_Node | Error: unexpected end of file`

Delete the .staging, Tdarr_Node and Tdarr_Server folders and retry. No user data is in those folders.

**Comment by DankMemeGuy** [comment]
> `Tdarr_Node | Error: unexpected end of file`
> 
> Delete the .staging, Tdarr_Node and Tdarr_Server folders and retry. No user data is in those folders.

I tried that with no avail. It's something with the downloading/unpacking procedure. I tried the updater application in an empty folder from scratch.



> Just tried this.
> If you go to the folde .Staging you will finde the zip file.
> Unpack that into the Tdarr_Node dir and you can run it.

Thank you so much this worked!

**Comment by DankMemeGuy** [comment]
Just wanted to let you know that it's been running for a day without any issue! Whatever bug you fixed worked great. thank you @HaveAGitGat

**Comment by HaveAGitGat** [comment]
Great news, looking forward to releasing this update :)

**Comment by DankMemeGuy** [comment]
This is the last message in the log before server crashed:

[2021-04-14T08:44:59.093] [ERROR] Tdarr_Server - Error: EMFILE: too many open files, open 'C:\Users\Name\Desktop\Tdarr\Tdarr_Server\node_modules\exiftool-vendored\dist\AsyncRetry.js'
    at Object.openSync (fs.js:461:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:487:32)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1217:22)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
[2021-04-14T08:45:07.571] [ERROR] Tdarr_Server - Error: EMFILE: too many open files, open 'C:\Users\Name\Desktop\Tdarr\Tdarr_Server\node_modules\batch-cluster\dist\Stream.js'
    at Object.openSync (fs.js:461:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:487:32)
    at Object.readFileSync (fs.js:364:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:683:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1217:22)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
[2021-04-14T08:45:19.857] [ERROR] Tdarr_Server - Error: Cannot find module 'C:/Users/Name/Desktop/Tdarr/Tdarr_Server/node_modules/exiftool-vendored'
Require stack:
- D:\snapshot\be\srcug\fileScanner\runExifToolSub.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (D:\snapshot\be\srcug\fileScanner\runExifToolSub.js:1:5545)
    at Module._compile (internal/modules/cjs/loader.js:1198:30)
    at Module._compile (pkg/prelude/bootstrap.js:1327:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)

**Comment by DankMemeGuy** [comment]
[2021-04-14T16:07:49.274] [ERROR] Tdarr_Server - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at D:\snapshot\be\srcug\fileScanners.js:1:18676
    at _0x2c3704 (D:\snapshot\be\srcug\fileScanners.js:1:7778)
    at Object.next (D:\snapshot\be\srcug\fileScanners.js:1:6088)
    at _0x4eb755 (D:\snapshot\be\srcug\fileScanners.js:1:5104)
internal/console/global.js:44
globalConsole[kBindStreamsLazy](process);
                               ^

TypeError: globalConsole[kBindStreamsLazy] is not a function
    at internal/console/global.js:44:32
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:276:7)
    at nativeModuleRequire (internal/bootstrap/loaders.js:305:14)
    at createGlobalConsole (internal/bootstrap/node.js:317:5)
    at internal/bootstrap/node.js:120:38

**Comment by DankMemeGuy** [comment]
These happen often too:

[2021-04-14T16:31:25.214] [ERROR] Tdarr_Server - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (D:\snapshot\be\node_modules\threads\dist\master\spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2021-04-14T16:32:36.679] [ERROR] Tdarr_Server - Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (D:\snapshot\be\node_modules\threads\dist\master\spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
production

**Comment by DankMemeGuy** [comment]
Running the server inside a cmd window has prevented it from crashing. So thank you for that tip!
