### ISSUE TITLE
Node unable to connect to server

### ISSUE THREAD

**Issue by goku-son** [HaveAGitGat/Tdarr#428]
Tdarr 2.00.09

I got tdarr server running and two nodes connected to it (1 local 1 other server). Both these nodes are Linux based. 

I am trying to add a 3rd node which runs as a docker image on Alpine Linux. Unfortunately, although configured as the two other nodes, I am getting these errors and the node does not connect:
```

[2021-04-13T17:45:11.758] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:11.759] [INFO] Tdarr_Node - Cloning plugins
tdarr_node    | [2021-04-13T17:45:14.877] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:17.997] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:21.117] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:24.237] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:27.357] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:30.477] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:31.793] [ERROR] Tdarr_Node - Error: getaddrinfo EAI_AGAIN github.com
tdarr_node    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
tdarr_node    | [2021-04-13T17:45:31.795] [INFO] Tdarr_Node - downloading plugins finished
tdarr_node    | (node:217) UnhandledPromiseRejectionWarning: Error: connect EHOSTUNREACH 10.0.100.99:8266
tdarr_node    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
tdarr_node    | (Use `Tdarr_Node --trace-warnings ...` to show where the warning was created)
tdarr_node    | (node:217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
tdarr_node    | (node:217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
tdarr_node    | [2021-04-13T17:45:33.598] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
tdarr_node    | [2021-04-13T17:45:36.717] [ERROR] Tdarr_Node - Server not alive IP:10.0.100.99 PORT:8266
```
Here is my config file:

```
alpine:~/tadarr_node# cat appdata/Tdarr_Node_Config.json
{
  "nodeID": "node3-alpinevm",
  "nodeIP": "10.0.100.102",
  "nodePort": "8267",
  "serverIP": "10.0.100.99",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ]

```
I can ssh to and from the server to the node. This node is on the same network as the other nodes and servers, so I am stumped as to why this node says it can’t see the tdarr server. Any ideas as to what to check or change would be greatly appreciated. Thanks in advance!

**Comment by jaycedk** [comment]
Hmm check the firewall settings, see if its blocking port 8267 and 8266

**Comment by HaveAGitGat** [comment]
`Error: getaddrinfo EAI_AGAIN github.com`

I think it’s a wider issue with the container config as the container can’t reach github.com when updating the plugins.

**Comment by goku-son** [comment]
It was in fact the docker container network config. Thanks for pointing me in the right direction!
