### ISSUE TITLE
Tdarr_Node stalling -> Error: EPERM: operation not permitted, lstat 

### ISSUE THREAD

**Issue by John2941** [HaveAGitGat/Tdarr#436]
Tdarr_Node stalls while transcoding shortly after (a few hours) this error is first encountered. This error appeared in my debug logs @ 5-2-21 19:59 and repeated every hour. The node worker looks like it was able to successfully transcode 4 video files before hanging up around 5-2-21 22:47:48. No entries as to why the transcoding event may have stalled. The folder is definitely writable and a 0 byte file named temp.zip is present in the directory. 

Here are some similar tickets: 
https://github.com/HaveAGitGat/Tdarr/issues/309
https://github.com/HaveAGitGat/Tdarr/issues/393

Tdarr version 2.00.10

My machine:
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042

Transcoding event logs that ended up stalling:
```
[2021-05-02T22:47:47.082] [INFO] Tdarr_Node - verbose:Sub-worker exit status received
[2021-05-02T22:47:47.106] [INFO] Tdarr_Node - verbose:Sub-worker exited
[2021-05-02T22:47:47.123] [WARN] Tdarr_Node - ☒File video not in required codec  
File in video size range 
File in video height range 
File in video width range  

[2021-05-02T22:47:47.123] [INFO] Tdarr_Node - verbose:Requesting item
[2021-05-02T22:47:47.124] [INFO] Tdarr_Node - verbose:Item request received
[2021-05-02T22:47:47.125] [INFO] Tdarr_Node - verbose:Getting new task
[2021-05-02T22:47:47.133] [INFO] Tdarr_Node - verbose:Item received
```

Repeated plugin logs every hour:
```
[2021-05-03T02:59:51.738] [INFO] Tdarr_Node - Cloning plugins
[2021-05-03T02:59:52.126] [INFO] Tdarr_Node - Finished downloading plugins!
[2021-05-03T02:59:52.126] [INFO] Tdarr_Node - downloading plugins finished
[2021-05-03T02:59:52.126] [ERROR] Tdarr_Node - Zip path does not exist!
[2021-05-03T02:59:54.132] [ERROR] Tdarr_Node - Plugin unzip failed!
[2021-05-03T03:59:51.267] [INFO] Tdarr_Node - Updating plugins
[2021-05-03T03:59:51.736] [ERROR] Tdarr_Node - Error: EPERM: operation not permitted, lstat 'C:/Users/User/Tdarr/Tdarr_Node/assets/app/plugins/temp.zip'
    at Object.lstatSync (fs.js:1026:3)
    at Object.fs.lstatSync (pkg/prelude/bootstrap.js:1010:33)
    at Object.lstatSync (D:\snapshot\tdarr_express_node\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.rimrafSync [as removeSync] (D:\snapshot\tdarr_express_node\node_modules\fs-extra\lib\remove\rimraf.js:228:18)
    at D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:8131
    at _0x26ed84 (D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:5570)
    at Object.next (D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:3849)
    at D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:3311
    at new Promise (<anonymous>)
    at __awaiter (D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:2671)
    at updatePlugins (D:\snapshot\tdarr_express_node\srcug\plugins\updatePluginThread.js:1:6261)
    at D:\snapshot\tdarr_express_node\node_modules\threads\dist\worker\index.js:109:26
    at Generator.next (<anonymous>)
    at D:\snapshot\tdarr_express_node\node_modules\threads\dist\worker\index.js:8:71
    at new Promise (<anonymous>)
    at D:\snapshot\tdarr_express_node\node_modules\threads\dist\worker\index.js:4:12
```

**Comment by ajw107** [comment]
This may sound silly, you have write permissions, but could you have disabled read permissions somehow?  Just it looks like it's bawking while either reading or updating the file stats.  Also maybe check to see if the file it is trying to read (the original, not the cache file) is still there.  I know I've ran into problems where sonarr has updated a file to a better resolution, therefore also changing it's filename, since tdarr added it the queue.

**Comment by HaveAGitGat** [comment]
Yeah double-check the permissions as mentioned above. Also haven't seen this error come up in recent version so please reopen if still occurring for you on 2.00.12, thanks.
