### ISSUE TITLE
Docker container won't restart. Hung on initializing database

### ISSUE THREAD

**Issue by natelandau** [HaveAGitGat/Tdarr#485]
**Describe the bug**
Restarting the Docker container does spikes CPU usage and never moves past initializing the database.  The CPU runs consistently at ~ 1000Mhz and the log repeats the following line every few minutes:

```
[WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI.
```

This bug is related to restarting the container with saved data.  Running the container with no saved data in `/app/server` works without issue and correctly creates the necessary files on first run and makes the webUI responsive.

I have been able to reproduce these issues using Docker on a Intel Mac as well as the Armv7 build on a RaspberryPi 4 without adding a media library or changing any settings.

**To Reproduce**
Run the `haveagitgat/tdarr_arm:2.00.10` container in Docker with a clean directory mapped to `/app/server`.  Stop the container.  Restart the container.

**Expected behavior**
The application and Web UI should become responsive and usable.

**Please provide the following information:**

Logs to STDERR:
```
chown: changing ownership of '/temp': Operation not permitted
chmod: cannot access '/app/Tdarr_Server/assets/app/fileScanner/': No such file or directory
(node:217) UnhandledPromiseRejectionWarning: Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (/snapshot/be/node_modules/threads/dist/master/spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(Use `Tdarr_Server --trace-warnings ...` to show where the warning was created)
(node:217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:217) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:217) UnhandledPromiseRejectionWarning: Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (/snapshot/be/node_modules/threads/dist/master/spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:217) UnhandledPromiseRejectionWarning: Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (/snapshot/be/node_modules/threads/dist/master/spawn.js:35:53)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:217) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

Server Config:
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "tdarrServer.service.consul",
  "handbrakePath": "HandBrakeCLI",
  "ffmpegPath": ""
}
```

Logs to STDOUT:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-setup-perms: executing... 
usermod: no changes

User uid:    1000
User gid:    995
-------------------------------------

Chowning the appassets, this make take some time
[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing... 
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Tdarr_Server
version: 2.00.10
Preparing environment
/app/configs/Tdarr_Server_Config.json
{
  serverPort: '8266',
  webUIPort: '8265',
  serverIP: 'tdarrServer.service.consul',
  handbrakePath: 'HandBrakeCLI',
  ffmpegPath: ''
}
Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:SettingsGlobalJSONDB

Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:LibrarySettingsJSONDB

Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:StatisticsJSONDB

Reading DB:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>(100%):1:StagedJSONDB

[2021-09-08T23:12:59.319] [WARN] Tdarr_Server - Running inside a Docker container
[2021-09-08T23:13:00.354] [INFO] Tdarr_Server - ffprobePath:/app/Tdarr_Server/node_modules/ffprobe-static/bin/linux/x64/ffprobe
[2021-09-08T23:13:00.373] [INFO] Tdarr_Server - exiftoolPath:/app/Tdarr_Server/node_modules/exiftool-vendored.pl/bin/exiftool
[2021-09-08T23:13:00.392] [INFO] Tdarr_Server - CCExtractorPath:/app/Tdarr_Server/assets/app/ccextractor/ccextractor
[2021-09-08T23:13:01.384] [INFO] Tdarr_Server - Tdarr started.
[2021-09-08T23:13:01.385] [INFO] Tdarr_Server - Tdarr documents folder:/app/server
[2021-09-08T23:13:01.385] [INFO] Tdarr_Server - Checking directories
[2021-09-08T23:13:01.392] [INFO] Tdarr_Server - Tdarr_Server listening at http://localhost:8266

[2021-09-08T23:13:02.018] [INFO] Tdarr_Server - ---------------Binary tests start----------------
[2021-09-08T23:13:02.089] [INFO] Tdarr_Server - handbrakePath:HandBrakeCLI
[2021-09-08T23:13:02.125] [INFO] Tdarr_Server - ffmpegPath:ffmpeg
[2021-09-08T23:13:02.175] [INFO] Tdarr_Server - mkvpropedit:mkvpropedit
[2021-09-08T23:13:02.176] [INFO] Tdarr_Server - Binary test 1: handbrakePath working
[2021-09-08T23:13:02.177] [INFO] Tdarr_Server - Binary test 2: ffmpegPath working
[2021-09-08T23:13:02.178] [ERROR] Tdarr_Server - Binary test 3: mkvpropeditPath not working
[2021-09-08T23:13:02.179] [INFO] Tdarr_Server - ---------------Binary tests end-------------------
[2021-09-08T23:13:02.391] [WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI.
production
[2021-09-08T23:17:43.131] [WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI.
```

Environment Variables:
```
          PUID        = "1000"
          PGID        = "1000"
          TZ          = "America/New_york"
          serverIP    = "tdarrServer.service.consul"
          serverPort  = "8266"
          webUIPort   = "8265"
          UMASK_SET   = "002"
```

**Comment by shokohsc** [comment]
Weird, it can take time to boot, sure but i cannot have the same behavior as you do, I fixed my case with that: https://github.com/just-containers/s6-overlay#customizing-s6-behaviour
and specifically with that environment variable: S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "120000" in my kubernetes deployment manifest.

**Comment by eltiel** [comment]
I too am experiencing this problem. It's almost unusable because after every restart:

- not only CPU usage spikes but the container maxes out RAM usage to the point it crashes my server (learnt this the hard way)
- any and all configuration cannot survive past a restart because the only way to restore the container is to wipe `/app/server`

**Comment by HaveAGitGat** [comment]
It's 10 sec dependency timeout due to the HDD not responding in time.  The quick fix is for you to set the env variable 'THREADS_WORKER_INIT_TIMEOUT' to something like 200000:

```
    environment:
      - THREADS_WORKER_INIT_TIMEOUT=200000
```

In 2.00.11 I've increased the default from 10 secs to 200 secs.
