### ISSUE TITLE
Permission denied using docker compose

### ISSUE THREAD

**Issue by Dr0mus** [HaveAGitGat/Tdarr#534]
**Describe the bug**
So I was using docker with portainer and tried to use the docker compose thing on the docs however it didn't run and gave me error messages when trying to startup up. This is a fresh install of everything; ubuntu, docker, portainer.

**To Reproduce**
On portainer go to stacks and copy and paste the docker compose thing into the input and click deploy the stack. (This is a fresh install)

**Please provide the following information:**
- Config files  No file in directory

- Log files  no file in directory

 - OS: Ubuntu

`Starting Tdarr_Node
version: 2.00.13
linux_arm64
/app/configs/Tdarr_Node_Config.json
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

Error: EACCES: permission denied, open '/app/configs/Tdarr_Node_Config.json.880726243'
    at Object.openSync (fs.js:497:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at writeFileSync (/snapshot/tdarr_express_node/node_modules/write-file-atomic/index.js:205:13)
    at saveConfig (/snapshot/tdarr_express_node/srcug/configs/configHandler.js:1:3313)
    at Object.<anonymous> (/snapshot/tdarr_express_node/srcug/configs/configHandler.js:1:4236)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/app/configs/Tdarr_Node_Config.json.880726243'
}`
error it spits out, I'm very new to linux my bad if I am missing something obvious.

**Comment by supersnellehenk** [comment]
Well, you can't copy paste it directly. Check if the volume mappings are pointing to the right location and the UID/GUID are correct. Stuff like this is never copy paste.

**Comment by Dr0mus** [comment]
yes fixed, I did volume mappings and the UID and GUID, thanks
