### ISSUE TITLE
Scanner: MediaInfo crashes with "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by tenfire** [HaveAGitGat/Tdarr#548]
**Description**
I have a MKV file that gives "RangeError: Maximum call stack size exceeded" in the Tdarr logs and the parameter file.mediaInfo = is not populated. Other files works great.

When I test with a standalone version of MediaInfo(v20.09) on the same file, it works.

Tdarr log:
```
[2022-01-31T17:49:05.819] [ERROR] Tdarr_Server - {}
RangeError: Maximum call stack size exceeded
    at readNextChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:82:29)
    at getChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:94:25)
    at readNextChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:83:29)
    at getChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:94:25)
    at readNextChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:83:29)
    at getChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:94:25)
    at readNextChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:83:29)
    at getChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:94:25)
    at readNextChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:83:29)
    at getChunk (/snapshot/be/node_modules/mediainfo.js/dist/mediainfo.js:94:25)
```
**To Reproduce**
Transcode the file again. I cannot upload the file unfortunately.

**Expected behavior**
MediaInfo parameter is populated as usual.

 - OS: Linux (Kubernetes/Docker)
 - Version 2.00.13

**Comment by HaveAGitGat** [comment]
Would need to open an issue on the medainfo repo: https://github.com/buzz/mediainfo.js

I think this can happen when there's not enough free ram when mediainfo is reading certain large files but not 100% sure.

I've bumped mediainfo.js to version 0.1.7 for .14 so perhaps the bug will be fixed.
