### ISSUE TITLE
No nodes detected after update to 2.00.18

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#597]
**Describe the bug**
The server does not detect any nodes after upgrading to 2.00.18. All nodes are running and connected to the server with no errors or warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/11021632/164066081-6cbb9be6-06ae-4437-9332-bc2e6df736d6.png)

**Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 01-setup-perms: executing... 
usermod: no changes

User uid:    1000
User gid:    100
-------------------------------------

Chowning the appassets, this may take some time
chmod: cannot access '/app/Tdarr_Node/assets/app/fileScanner/': No such file or directory
chmod: cannot access '/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe': No such file or directory
[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing... 
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Tdarr_Server
[2022-04-19T12:58:47.468] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:R/W Accessible
[2022-04-19T12:58:47.469] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading
[2022-04-19T12:58:47.470] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Adding
[2022-04-19T12:58:47.471] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):1:SettingsGlobalJSONDB::Reading done
[2022-04-19T12:58:47.471] [INFO] Tdarr_Server - Reading DB:__________(0%):1:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/218d4661a32d97b548eb7efd58b4c4cf45e14ee4.json:R/W Accessible
[2022-04-19T12:58:47.471] [INFO] Tdarr_Server - Reading DB:__________(0%):1:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/218d4661a32d97b548eb7efd58b4c4cf45e14ee4.json:Reading
[2022-04-19T12:58:47.472] [INFO] Tdarr_Server - Reading DB:__________(0%):1:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/218d4661a32d97b548eb7efd58b4c4cf45e14ee4.json:Adding
[2022-04-19T12:58:47.472] [INFO] Tdarr_Server - Reading DB:>>________(15%):2:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/724aefdc6a6e40fe156b919e174ea757d1f02dbb.json:R/W Accessible
[2022-04-19T12:58:47.472] [INFO] Tdarr_Server - Reading DB:>>________(15%):2:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/724aefdc6a6e40fe156b919e174ea757d1f02dbb.json:Reading
[2022-04-19T12:58:47.473] [INFO] Tdarr_Server - Reading DB:>>________(15%):2:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/724aefdc6a6e40fe156b919e174ea757d1f02dbb.json:Adding
[2022-04-19T12:58:47.473] [INFO] Tdarr_Server - Reading DB:>>>_______(29%):3:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/8b4e86a4a5343231f8b54ce3bebf76ec727fa2ba.json:R/W Accessible
[2022-04-19T12:58:47.473] [INFO] Tdarr_Server - Reading DB:>>>_______(29%):3:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/8b4e86a4a5343231f8b54ce3bebf76ec727fa2ba.json:Reading
[2022-04-19T12:58:47.473] [INFO] Tdarr_Server - Reading DB:>>>_______(29%):3:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/8b4e86a4a5343231f8b54ce3bebf76ec727fa2ba.json:Adding
[2022-04-19T12:58:47.474] [INFO] Tdarr_Server - Reading DB:>>>>>_____(43%):4:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c76e94b6839a8837e891a2a94294de7409fb2fa5.json:R/W Accessible
[2022-04-19T12:58:47.474] [INFO] Tdarr_Server - Reading DB:>>>>>_____(43%):4:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c76e94b6839a8837e891a2a94294de7409fb2fa5.json:Reading
[2022-04-19T12:58:47.474] [INFO] Tdarr_Server - Reading DB:>>>>>_____(43%):4:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c76e94b6839a8837e891a2a94294de7409fb2fa5.json:Adding
[2022-04-19T12:58:47.474] [INFO] Tdarr_Server - Reading DB:>>>>>>____(58%):5:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c89ecd77cbf2a62fc7d206a0df0c17944f14250d.json:R/W Accessible
[2022-04-19T12:58:47.474] [INFO] Tdarr_Server - Reading DB:>>>>>>____(58%):5:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c89ecd77cbf2a62fc7d206a0df0c17944f14250d.json:Reading
[2022-04-19T12:58:47.475] [INFO] Tdarr_Server - Reading DB:>>>>>>____(58%):5:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/c89ecd77cbf2a62fc7d206a0df0c17944f14250d.json:Adding
[2022-04-19T12:58:47.475] [INFO] Tdarr_Server - Reading DB:>>>>>>>>__(72%):6:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/dc758d773f72c244f17f90cc3ff0dd3ab2b49c75.json:R/W Accessible
[2022-04-19T12:58:47.475] [INFO] Tdarr_Server - Reading DB:>>>>>>>>__(72%):6:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/dc758d773f72c244f17f90cc3ff0dd3ab2b49c75.json:Reading
[2022-04-19T12:58:47.476] [INFO] Tdarr_Server - Reading DB:>>>>>>>>__(72%):6:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/dc758d773f72c244f17f90cc3ff0dd3ab2b49c75.json:Adding
[2022-04-19T12:58:47.476] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(86%):7:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/f135f5836f484b8e5d1f4c2f40c233f8c9aace7d.json:R/W Accessible
[2022-04-19T12:58:47.476] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(86%):7:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/f135f5836f484b8e5d1f4c2f40c233f8c9aace7d.json:Reading
[2022-04-19T12:58:47.476] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(86%):7:LibrarySettingsJSONDB:/app/server/Tdarr/DB2/LibrarySettingsJSONDB/f135f5836f484b8e5d1f4c2f40c233f8c9aace7d.json:Adding
[2022-04-19T12:58:47.476] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):7:LibrarySettingsJSONDB::Reading done
[2022-04-19T12:58:47.477] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/5af125a0fe9b5590aea3312f5711859739085d36.json:R/W Accessible
[2022-04-19T12:58:47.477] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/5af125a0fe9b5590aea3312f5711859739085d36.json:Reading
[2022-04-19T12:58:47.478] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/5af125a0fe9b5590aea3312f5711859739085d36.json:Adding
[2022-04-19T12:58:47.478] [INFO] Tdarr_Server - Reading DB:>>________(17%):2:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/b2f0a087b18db69b09c44842af779ef9966037e2.json:R/W Accessible
[2022-04-19T12:58:47.478] [INFO] Tdarr_Server - Reading DB:>>________(17%):2:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/b2f0a087b18db69b09c44842af779ef9966037e2.json:Reading
[2022-04-19T12:58:47.478] [INFO] Tdarr_Server - Reading DB:>>________(17%):2:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/b2f0a087b18db69b09c44842af779ef9966037e2.json:Adding
[2022-04-19T12:58:47.478] [INFO] Tdarr_Server - Reading DB:>>>>______(34%):3:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c400d65e112b2f4b8c8306091ffd9fb05499320b.json:R/W Accessible
[2022-04-19T12:58:47.479] [INFO] Tdarr_Server - Reading DB:>>>>______(34%):3:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c400d65e112b2f4b8c8306091ffd9fb05499320b.json:Reading
[2022-04-19T12:58:47.479] [INFO] Tdarr_Server - Reading DB:>>>>______(34%):3:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c400d65e112b2f4b8c8306091ffd9fb05499320b.json:Adding
[2022-04-19T12:58:47.479] [INFO] Tdarr_Server - Reading DB:>>>>>_____(50%):4:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c57178efd30c5dd86019c84414fab3c01ec9e1e6.json:R/W Accessible
[2022-04-19T12:58:47.479] [INFO] Tdarr_Server - Reading DB:>>>>>_____(50%):4:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c57178efd30c5dd86019c84414fab3c01ec9e1e6.json:Reading
[2022-04-19T12:58:47.480] [INFO] Tdarr_Server - Reading DB:>>>>>_____(50%):4:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/c57178efd30c5dd86019c84414fab3c01ec9e1e6.json:Adding
[2022-04-19T12:58:47.480] [INFO] Tdarr_Server - Reading DB:>>>>>>>___(67%):5:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/cda86e0e3240a37147339d2acfe17ee86cab1947.json:R/W Accessible
[2022-04-19T12:58:47.480] [INFO] Tdarr_Server - Reading DB:>>>>>>>___(67%):5:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/cda86e0e3240a37147339d2acfe17ee86cab1947.json:Reading
[2022-04-19T12:58:47.481] [INFO] Tdarr_Server - Reading DB:>>>>>>>___(67%):5:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/cda86e0e3240a37147339d2acfe17ee86cab1947.json:Adding
[2022-04-19T12:58:47.481] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(84%):6:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/ee59263453fcaba49c65de5579fa0364c366de12.json:R/W Accessible
[2022-04-19T12:58:47.481] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(84%):6:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/ee59263453fcaba49c65de5579fa0364c366de12.json:Reading
[2022-04-19T12:58:47.481] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>_(84%):6:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/ee59263453fcaba49c65de5579fa0364c366de12.json:Adding
[2022-04-19T12:58:47.481] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):6:NodeJSONDB::Reading done
[2022-04-19T12:58:47.482] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:R/W Accessible
[2022-04-19T12:58:47.482] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:Reading
[2022-04-19T12:58:47.482] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:Adding
[2022-04-19T12:58:47.482] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):1:StatisticsJSONDB::Reading done
[2022-04-19T12:58:47.628] [INFO] Tdarr_Server - /app/configs/Tdarr_Server_Config.json
[2022-04-19T12:58:47.639] [INFO] Tdarr_Server - {
  serverPort: '8266',
  webUIPort: '8265',
  serverIP: '192.168.10.112',
  handbrakePath: '',
  ffmpegPath: '',
  logLevel: 'INFO'
}
[2022-04-19T12:58:48.045] [INFO] Tdarr_Server - version: 2.00.18
[2022-04-19T12:58:48.045] [INFO] Tdarr_Server - linux_x64_docker_true
[2022-04-19T12:58:48.045] [INFO] Tdarr_Server - Preparing environment
[2022-04-19T12:58:48.411] [INFO] Tdarr_Server - Tdarr started.
[2022-04-19T12:58:48.411] [INFO] Tdarr_Server - Tdarr documents folder:/app/server
[2022-04-19T12:58:48.411] [INFO] Tdarr_Server - Checking directories
[2022-04-19T12:58:48.413] [INFO] Tdarr_Server - Tdarr_Server listening at http://192.168.10.112:8266
[2022-04-19T12:58:48.413] [TRACE] Tdarr_Server - 
    --------------------------------------------------------------------------
    --------------------------------------------------------------------------
    
    Tdarr_WebUI running at http://localhost:8265
    
    --------------------------------------------------------------------------
    --------------------------------------------------------------------------
      
[2022-04-19T12:58:49.731] [INFO] Tdarr_Server - ---------------Binary tests start----------------
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - handbrakePath:HandBrakeCLI
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - ffmpegPath:tdarr-ffmpeg
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - mkvpropedit:mkvpropedit
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - Binary test 1: handbrakePath working
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - Binary test 2: ffmpegPath working
[2022-04-19T12:58:49.733] [INFO] Tdarr_Server - ---------------Binary tests end-------------------
[2022-04-19T12:58:49.742] [INFO] Tdarr_Server - ---------------Scanner tests start----------------
[2022-04-19T12:58:49.747] [INFO] Tdarr_Server - Scanner test: Scanning file start
[2022-04-19T12:58:54.432] [ERROR] Tdarr_Server - Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:841:20)
    at ChildProcess.target.send (internal/child_process.js:712:19)
    at Socket.<anonymous> (/snapshot/app/srcug/fileScanner/runCCExtractor.js:1:9592)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[2022-04-19T12:58:54.436] [FATAL] Tdarr_Server - Error in main thread:Error: write EPIPE
[2022-04-19T12:58:54.510] [INFO] Tdarr_Server - Scanner test: Scanning file end
[2022-04-19T12:58:54.510] [INFO] Tdarr_Server - Scanner test 1: FFprobe working
[2022-04-19T12:58:54.510] [INFO] Tdarr_Server - Scanner test 2: Exiftool working
[2022-04-19T12:58:54.510] [INFO] Tdarr_Server - Scanner test 3: Mediainfo working
[2022-04-19T12:58:54.510] [INFO] Tdarr_Server - Scanner test 4: CCExtractor working
[2022-04-19T12:58:54.511] [INFO] Tdarr_Server - ---------------Scanner tests end----------------
```
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 01-setup-perms: executing... 
usermod: no changes

User uid:    1000
User gid:    100
-------------------------------------

Chowning the appassets, this make take some time
chmod: cannot access '/app/Tdarr_Node/assets/app/fileScanner/': No such file or directory
chmod: cannot access '/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe': No such file or directory
[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing... 
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Tdarr_Node
[services.d] done.
version: 2.00.16
linux_x64_docker_true
[2022-04-19T12:48:03.571] [INFO] Tdarr_Node - /app/configs/Tdarr_Node_Config.json
[2022-04-19T12:48:03.580] [INFO] Tdarr_Node - {
  nodeID: 'PLEX',
  nodeIP: '192.168.10.110',
  nodePort: '8267',
  serverIP: '192.168.10.112',
  serverPort: '8266',
  handbrakePath: '',
  ffmpegPath: '',
  mkvpropeditPath: '',
  pathTranslators: [ { server: '', node: '' } ],
  platform_arch: 'linux_x64_docker_true',
  logLevel: 'INFO'
}
[2022-04-19T12:48:03.668] [INFO] Tdarr_Node - Starting Tdarr_Node
[2022-04-19T12:48:03.668] [INFO] Tdarr_Node - Preparing environment
[2022-04-19T12:48:03.780] [INFO] Tdarr_Node - Updating plugins
[2022-04-19T12:48:03.787] [INFO] Tdarr_Node - Tdarr_Node listening at http://192.168.10.110:8267
[2022-04-19T12:48:03.845] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2022-04-19T12:48:03.852] [INFO] Tdarr_Node - handbrakePath:HandBrakeCLI
[2022-04-19T12:48:03.858] [INFO] Tdarr_Node - ffmpegPath:ffmpeg
[2022-04-19T12:48:03.864] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2022-04-19T12:48:03.864] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2022-04-19T12:48:03.865] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2022-04-19T12:48:03.865] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2022-04-19T12:48:04.237] [INFO] Tdarr_Node - Cloning plugins
[2022-04-19T12:48:04.622] [INFO] Tdarr_Node - Finished downloading plugins!
[2022-04-19T12:48:07.881] [INFO] Tdarr_Node - [3.645s]Plugin update finished
```
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 01-setup-perms: executing... 
usermod: no changes

User uid:    1000
User gid:    100
-------------------------------------

Chowning the appassets, this make take some time
chmod: cannot access '/app/Tdarr_Node/assets/app/fileScanner/': No such file or directory
chmod: cannot access '/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe': No such file or directory
[cont-init.d] 01-setup-perms: exited 0.
[cont-init.d] 02-hw-transcoding: executing... 
[cont-init.d] 02-hw-transcoding: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Tdarr_Node
version: 2.00.16
linux_x64_docker_true
[2022-04-19T12:47:29.554] [INFO] Tdarr_Node - /app/configs/Tdarr_Node_Config.json
[2022-04-19T12:47:29.567] [INFO] Tdarr_Node - {
  nodeID: 'NVR',
  nodeIP: '192.168.10.111',
  nodePort: '8267',
  serverIP: '192.168.10.112',
  serverPort: '8266',
  handbrakePath: '',
  ffmpegPath: '',
  mkvpropeditPath: '',
  pathTranslators: [ { server: '', node: '' } ],
  platform_arch: 'linux_x64_docker_true',
  logLevel: 'INFO'
}
[2022-04-19T12:47:29.677] [INFO] Tdarr_Node - Starting Tdarr_Node
[2022-04-19T12:47:29.677] [INFO] Tdarr_Node - Preparing environment
[2022-04-19T12:47:29.856] [INFO] Tdarr_Node - Updating plugins
[2022-04-19T12:47:29.867] [INFO] Tdarr_Node - Tdarr_Node listening at http://192.168.10.111:8267
[2022-04-19T12:47:29.967] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2022-04-19T12:47:29.973] [INFO] Tdarr_Node - handbrakePath:HandBrakeCLI
[2022-04-19T12:47:29.982] [INFO] Tdarr_Node - ffmpegPath:ffmpeg
[2022-04-19T12:47:29.990] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2022-04-19T12:47:29.990] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2022-04-19T12:47:29.990] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2022-04-19T12:47:29.991] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2022-04-19T12:47:30.523] [INFO] Tdarr_Node - Cloning plugins
[2022-04-19T12:47:30.998] [INFO] Tdarr_Node - Finished downloading plugins!
[2022-04-19T12:47:34.528] [INFO] Tdarr_Node - [4.006s]Plugin update finished
```

 - OS: LSIO Docker Container
 - Version [e.g. 2.00.18]

**Comment by HaveAGitGat** [comment]
Thanks, the issue is you need to update the node to 2.00.18 as that is what the server is running. Server and node versions should always be the same. 

It would normally show you a version mismatch error but the way in which the server and nodes communicate has changed in .17 so the node can't contact the server in the first place.

**Comment by tehniemer** [comment]
Ha! easy enough. I was wondering why Watchtower updated the server but not the nodes, then I noticed the node images were updated in docker hub after Watchtower ran for the day. Doh!
