### ISSUE TITLE
Issues with transcoding using a Windows node and unraid server container

### ISSUE THREAD

**Issue by jbitGit** [HaveAGitGat/Tdarr#663]
I am having an issue where the status window in Tdarr is just a spinning wheel and the ETA is stuck at calculating. This is using a Windows node and a unraid docker container server. The server itself works with a unraid docker node worker. The logs in the server show no errors

[2022-07-11T00:02:22.491] [INFO] Tdarr_Node - version: 2.00.18

[2022-07-11T00:02:22.492] [INFO] Tdarr_Node - win32_x64_docker_false

[2022-07-11T00:02:22.492] [INFO] Tdarr_Node - Starting Tdarr_Node

[2022-07-11T00:02:22.492] [INFO] Tdarr_Node - Preparing environment

[2022-07-11T00:02:22.493] [INFO] Tdarr_Node - Path translator: Checking Node path: Y:/

[2022-07-11T00:02:22.494] [INFO] Tdarr_Node - Updating plugins

[2022-07-11T00:02:22.508] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: Y:/

[2022-07-11T00:02:22.509] [INFO] Tdarr_Node - Path translator: Checking Node path: Z:/

[2022-07-11T00:02:22.525] [INFO] Tdarr_Node - Path translator: Success: Node path can be accessed: Z:/

[2022-07-11T00:02:22.549] [INFO] Tdarr_Node - Node connected & registered

[2022-07-11T00:02:22.624] [INFO] Tdarr_Node - ---------------Binary tests start----------------

[2022-07-11T00:02:22.625] [INFO] Tdarr_Node - handbrakePath:C:/Users/joebu/Downloads/tdarr/Tdarr_Node/assets/app/HandBrakeCLI.exe

[2022-07-11T00:02:22.625] [INFO] Tdarr_Node - ffmpegPath:C:/Users/joebu/Downloads/tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe

[2022-07-11T00:02:22.625] [INFO] Tdarr_Node - mkvpropedit:C:/Users/joebu/Downloads/tdarr/Tdarr_Node/assets/app/mkvpropedit/windows/mkvpropedit.exe

[2022-07-11T00:02:22.625] [INFO] Tdarr_Node - Binary test 1: handbrakePath working

[2022-07-11T00:02:22.626] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working

[2022-07-11T00:02:22.626] [INFO] Tdarr_Node - ---------------Binary tests end-------------------

[2022-07-11T00:02:22.788] [INFO] Tdarr_Node - Cloning plugins

[2022-07-11T00:02:23.110] [INFO] Tdarr_Node - Finished downloading plugins!

[2022-07-11T00:02:26.691] [INFO] Tdarr_Node - [3904]Plugin update finished

but on the node itself it gives the following error when trying to load a file.

[2022-07-11T00:02:23.110] [INFO] Tdarr_Node - Finished downloading plugins!
[2022-07-11T00:02:26.691] [INFO] Tdarr_Node - [3904]Plugin update finished
(node:19508) UnhandledPromiseRejectionWarning: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal (child_process.js:911:17)
    at Object.spawn (pkg/prelude/bootstrap.js:1944:27)
    at Object.fork (child_process.js:153:25)
    at launchWorker (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:29685)
    at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:40317
    at _0x2c23c7 (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:10643)
    at Object.next (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8962)
    at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8430
(Use `Tdarr_Node --trace-warnings ...` to show where the warning was created)
(node:19508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by HaveAGitGat** [comment]
What are your library settings? Which plugins are you using?

**Comment by 800kingderek** [comment]
I am having the same error getting thrown every few minutes or so.  
<img width="236" alt="tdarr plugin stack" src="https://user-images.githubusercontent.com/83919050/187322334-b057a483-be6f-446e-8d3a-8d5a8dd6b979.png">
<img width="1906" alt="tdarr errors" src="https://user-images.githubusercontent.com/83919050/187322434-c3119f1b-a6ff-4c0a-a168-8b9c3a5f3856.png">

**Comment by HaveAGitGat** [comment]
Should be fixed in 2.00.20

https://docs.tdarr.io/docs/releases/changing-version#using-a-native-package-pre-release

**Comment by HaveAGitGat** [comment]
2.00.20 released
