### ISSUE TITLE
Cannot read property 'ffProbeRead' of undefined

### ISSUE THREAD

**Issue by RedSpid3r** [HaveAGitGat/Tdarr#670]
**Describe the bug**
Transcode: Success/Not required tab is not updating. When an item is successfully transcoded it is never added to the "Transcode: Success/Not required" tab. ALL the jobs (5552) in this tab are showing a time only and those with job reports are all listed as being dated "2022-07-12"

**To Reproduce**
Transcode an item

**Expected behavior**
Item is added to this list upon successful transcode.

 - OS: Unraid / Docker
 - Browser: FireFox
 - Version: 2.00.18

**Additional context**

**Comment by HaveAGitGat** [comment]
Do you have a screenshot? Are the files still in the staging section?

**Comment by RedSpid3r** [comment]
> Do you have a screenshot? Are the files still in the staging section?

Files are removed from the staging section upon completion. 

While I was trying this up, another transcode was completed but also does not appear in Transcode: Success/Not required tab, however if I browse to `server\Tdarr\DB2\JobReports\<id>` I see the following in the end of the log:

```
2022-08-09T16:54:32.235Z gaOoDm_KmlT:Removing item from staging section
2022-08-09T16:54:32.236Z gaOoDm_KmlT:Scanning new file
2022-08-09T16:54:32.238Z gaOoDm_KmlT:Running new file through post processing plugins
2022-08-09T16:54:32.240Z gaOoDm_KmlT:
2022-08-09T16:54:32.242Z gaOoDm_KmlT:Removing original item from database
2022-08-09T16:54:32.244Z gaOoDm_KmlT:Adding new file to database
2022-08-09T16:54:32.246Z gaOoDm_KmlT:Error encountered TypeError: Cannot read property 'ffProbeRead' of undefined
```

**Comment by HaveAGitGat** [comment]
Are the files in the transcode error tab?

Try running it on a h264 sample from here: https://tdarr.io/samples/

That way can see if it’s an issue with your specific files or not.

**Comment by RedSpid3r** [comment]
I set up a new library and transcoded the sample h264 files without issue, went back to compare the config of the new library vs the old and it seems there had been a single `.` added into the "Output Folder" path, once I removed this "Success/Not required" is now updating again

**Comment by RedSpid3r** [comment]
Update, tried to transcode some stuff this evening and getting the same issue. Server logs:

```
[2022-08-10T20:48:34.683] [ERROR] Tdarr_Server - TypeError: Cannot read property 'ffProbeRead' of undefined
    at stripFile (/snapshot/app/srcug/stripFile.js:1:3585)
    at /snapshot/app/srcug/api/nodeRelay/cacheCopyService.js:1:28764
    at _0x5cf754 (/snapshot/app/srcug/api/nodeRelay/cacheCopyService.js:1:8301)
    at Object.next (/snapshot/app/srcug/api/nodeRelay/cacheCopyService.js:1:6640)
    at _0x446293 (/snapshot/app/srcug/api/nodeRelay/cacheCopyService.js:1:5619)

```

**Comment by RedSpid3r** [comment]
@HaveAGitGat Just wondering if there was any update? I still can't transcode due to the above error server-side.

TIA

**Comment by HaveAGitGat** [comment]
What is your plugin stack? Best to post the full job report log so can have a look at the details.

**Comment by RedSpid3r** [comment]
Plugin Stack:
![image](https://user-images.githubusercontent.com/12657277/187451038-0757ffa2-72dd-467c-8f74-c501a75d4713.png)


Job report:
[QH8corSQGPG()2.00.18()transcode()0XSg4UZVJIm()1661376255371.txt](https://github.com/HaveAGitGat/Tdarr/files/9453250/QH8corSQGPG.2.00.18.transcode.0XSg4UZVJIm.1661376255371.txt)

**Comment by RedSpid3r** [comment]
any update on this?

**Comment by HaveAGitGat** [comment]
2.00.19 released, reopen if needed thanks.
