### ISSUE TITLE
Fail to work from Windows 10 node to Windows 10 server

### ISSUE THREAD

**Issue by killo3967** [HaveAGitGat/Tdarr#728]
I have the same problem.

My configuration in the server (Windows 10) is
library -> T:
transcode cache -> D:\TDARR_transcodecache

Localy in the server all works perfect, but no in othe windows node.
In the remote node I map the units

net use t: \server\t$
net use d: \server\d$

So the local and the remotes units are the same.

I also confirm the read/write access from the remote node to the server units D: and T:

In the remote node, the node configuration file i only modify the ip address and do not made any translation.

But the result is:
[2023-01-14T22:45:59.902] [INFO] Tdarr_Node - version: 2.00.18
[2023-01-14T22:45:59.903] [INFO] Tdarr_Node - win32_x64_docker_false
[2023-01-14T22:45:59.904] [INFO] Tdarr_Node - Starting Tdarr_Node
[2023-01-14T22:45:59.904] [INFO] Tdarr_Node - Preparing environment
[2023-01-14T22:45:59.906] [INFO] Tdarr_Node - Updating plugins
[2023-01-14T22:45:59.974] [INFO] Tdarr_Node - Node connected & registered
[2023-01-14T22:46:00.569] [INFO] Tdarr_Node - Cloning plugins
[2023-01-14T22:46:00.734] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-01-14T22:46:00.734] [INFO] Tdarr_Node - handbrakePath:C:/Tdarr/Tdarr_Node/assets/app/HandBrakeCLI.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - ffmpegPath:C:/Tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - mkvpropedit:C:/Tdarr/Tdarr_Node/assets/app/mkvpropedit/windows/mkvpropedit.exe
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-01-14T22:46:00.735] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-01-14T22:46:01.330] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-01-14T22:46:05.475] [INFO] Tdarr_Node - [4909]Plugin update finished
[2023-01-14T22:46:05.713] [ERROR] Tdarr_Node - Error: ENOENT: no such file or directory, access 'T:/Érase una vez (2011)/Érase una vez - 4x01 - El cuento de las dos hermanas.avi'
at Object.accessSync (fs.js:228:3)
at Object.accessSync (pkg/prelude/bootstrap.js:1474:34)
at _0x274ea4 (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:49056)
at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:49485
at _0x2c23c7 (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:10643)
at Object.next (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8962)
at C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:8430
at new Promise ()
at __awaiter (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:7746)
at preProcessFile (C:\snapshot\tdarr_express_node\srcug\workers\worker1.js:1:48510) {
errno: -4058,
syscall: 'access',
code: 'ENOENT',
path: 'T:/Érase una vez (2011)/Érase una vez - 4x01 - El cuento de las dos hermanas.avi'
}

Of course, i am doing something wrong, but what?

**Comment by HaveAGitGat** [comment]
Are you running the Node as admin? This can prevent it from seeing network shares so make sure to not run as admin.

**Comment by killo3967** [comment]
I have done all the combinations with the node and the server, i mean:

CASE1 -> server: user admin                                       node: user admin, user with user with admin rights and user without admin rights
CASE2 -> server: local user with admin rights              node: user admin, user with user with admin rights and user without admin rights
CASE3-> server: local user without admin rights         node: user admin, user with user with admin rights and user without admin rights

In some cases (CASE1 and CASE2) I have had to modify the write/read rights of the directories to give the user access to the files. 
In the case of the server with a user without administrative rights (CASE3), the server did not work, even modifying the access permissions to the directories.

**Comment by HaveAGitGat** [comment]
Hi please try 2.00.20 and post job report (https://docs.tdarr.io/docs/other/job-reports/) and reopen if needed, ty.
