### ISSUE TITLE
tdarr server dies on start

### ISSUE THREAD

**Issue by uhthomas** [HaveAGitGat/Tdarr#761]
**Describe the bug**

I can't get the tdarr container to work. It dies as soon as it starts.

`ghcr.io/haveagitgat/tdarr:2.00.20.1@sha256:75e128ebb10f769615e5878fc2dad618adbd17a01e3a96060338e28dc8978a1c`

**To Reproduce**
Steps to reproduce the behavior: Try and start the container.

**Expected behavior**
It should start.

**Screenshots**

**Please provide the following information:**
- Config files N/A - default

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

```
❯ k -n media logs tdarr-6969f9bb5c-6gnqn
cont-init: info: running /etc/cont-init.d/01-setup-perms
[migrations] started
[migrations] no migrations found
usermod: no changes

User uid:    1000
User gid:    3000
-------------------------------------

chown: First run and CHOWN_ON_START != false, chowning /app, ffmpeg and ffprobe, this may take some time
chmod: cannot access '/app/Tdarr_Node/assets/app/fileScanner/': No such file or directory
chmod: cannot access '/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe': No such file or directory
cont-init: info: /etc/cont-init.d/01-setup-perms exited 0
cont-init: info: running /etc/cont-init.d/02-hw-transcoding
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    3000
───────────────────────────────────────

cont-init: info: /etc/cont-init.d/02-hw-transcoding exited 0
[custom-init] No custom files found, skipping...
services-up: info: copying legacy longrun tdarr_node (no readiness notification)
services-up: info: copying legacy longrun tdarr_server (no readiness notification)
[ls.io-init] done.
Starting Tdarr_Server
Starting Tdarr_Node
[2023-04-05T13:39:59.009] [INFO] Tdarr_Node - /app/configs/Tdarr_Node_Config.json
[2023-04-05T13:39:59.175] [INFO] Tdarr_Node - {
  nodeName: 'tdarr-6969f9bb5c-6gnqn',
  serverIP: '0.0.0.0',
  serverPort: '8266',
  handbrakePath: '',
  ffmpegPath: '',
  mkvpropeditPath: '',
  pathTranslators: [ { server: '', node: '' } ],
  logLevel: 'INFO',
  priority: -1,
  platform_arch_isdocker: 'linux_x64_docker_false',
  processPid: 204,
  nodeID: 'LGySuITJY'
}
[2023-04-05T13:39:59.337] [INFO] Tdarr_Node - version: 2.00.20
[2023-04-05T13:39:59.337] [INFO] Tdarr_Node - platform_arch_isdocker: linux_x64_docker_false
[2023-04-05T13:39:59.344] [INFO] Tdarr_Node - Starting Tdarr_Node
[2023-04-05T13:39:59.344] [INFO] Tdarr_Node - Preparing environment
[2023-04-05T13:39:59.786] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:R/W Accessible
[2023-04-05T13:39:59.792] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Reading
[2023-04-05T13:39:59.793] [INFO] Tdarr_Server - Reading DB:__________(0%):1:SettingsGlobalJSONDB:/app/server/Tdarr/DB2/SettingsGlobalJSONDB/afdf79ef24e7f6f173693057d0c2f3c07b0d3a3c.json:Adding
[2023-04-05T13:39:59.794] [INFO] Tdarr_Node - Updating plugins
[2023-04-05T13:39:59.795] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):1:SettingsGlobalJSONDB::Reading done
[2023-04-05T13:39:59.795] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):0:LibrarySettingsJSONDB::Reading done
[2023-04-05T13:39:59.797] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/a25d393ad4ec81357504203bbc55879269cdd670.json:R/W Accessible
[2023-04-05T13:39:59.797] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/a25d393ad4ec81357504203bbc55879269cdd670.json:Reading
[2023-04-05T13:39:59.797] [INFO] Tdarr_Server - Reading DB:__________(0%):1:NodeJSONDB:/app/server/Tdarr/DB2/NodeJSONDB/a25d393ad4ec81357504203bbc55879269cdd670.json:Adding
[2023-04-05T13:39:59.798] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):1:NodeJSONDB::Reading done
[2023-04-05T13:39:59.798] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:R/W Accessible
[2023-04-05T13:39:59.798] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:Reading
[2023-04-05T13:39:59.799] [INFO] Tdarr_Server - Reading DB:__________(0%):1:StatisticsJSONDB:/app/server/Tdarr/DB2/StatisticsJSONDB/3d18b2ea89fa5357cf6423b4e6985b46fa10195e.json:Adding
[2023-04-05T13:39:59.799] [INFO] Tdarr_Server - Reading DB:>>>>>>>>>>(100%):1:StatisticsJSONDB::Reading done
[2023-04-05T13:39:59.836] [ERROR] Tdarr_Node - Node connection error to :0.0.0.0:8266
[2023-04-05T13:39:59.836] [ERROR] Tdarr_Node - TransportError: xhr poll error
    at Polling.onError (/snapshot/node/node_modules/engine.io-client/build/cjs/transport.js:45:37)
    at Request.<anonymous> (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:251:18)
    at Request.<anonymous> (/snapshot/node/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:352:14)
    at Timeout._onTimeout (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:325:30)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  description: 0,
  context: XMLHttpRequest {
    UNSENT: 0,
    OPENED: 1,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    DONE: 4,
    readyState: 4,
    onreadystatechange: [Function (anonymous)],
    responseText: 'Error: connect ECONNREFUSED 0.0.0.0:8266\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)',
    responseXML: '',
    status: 0,
    statusText: Error: connect ECONNREFUSED 0.0.0.0:8266
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -111,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '0.0.0.0',
      port: 8266
    },
    open: [Function (anonymous)],
    setDisableHeaderCheck: [Function (anonymous)],
    setRequestHeader: [Function (anonymous)],
    getResponseHeader: [Function (anonymous)],
    getAllResponseHeaders: [Function (anonymous)],
    getRequestHeader: [Function (anonymous)],
    send: [Function (anonymous)],
    handleError: [Function (anonymous)],
    abort: [Function (anonymous)],
    addEventListener: [Function (anonymous)],
    removeEventListener: [Function (anonymous)],
    dispatchEvent: [Function (anonymous)]
  },
  type: 'TransportError'
}
[2023-04-05T13:40:00.149] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-04-05T13:40:00.149] [INFO] Tdarr_Node - handbrakePath:HandBrakeCLI
[2023-04-05T13:40:00.149] [INFO] Tdarr_Node - ffmpegPath:/app/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg
[2023-04-05T13:40:00.149] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2023-04-05T13:40:00.149] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2023-04-05T13:40:00.150] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-04-05T13:40:00.150] [INFO] Tdarr_Node - Binary test 3: mkvpropeditPath working
[2023-04-05T13:40:00.150] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-04-05T13:40:00.259] [INFO] Tdarr_Server - /app/configs/Tdarr_Server_Config.json
[2023-04-05T13:40:00.398] [INFO] Tdarr_Server - {
  serverPort: '8266',
  webUIPort: '8265',
  serverIP: '0.0.0.0',
  handbrakePath: '',
  ffmpegPath: '',
  logLevel: 'INFO',
  mkvpropeditPath: '',
  ccextractorPath: '',
  openBrowser: true
}
[2023-04-05T13:40:01.261] [INFO] Tdarr_Server - version: 2.00.20
[2023-04-05T13:40:01.261] [INFO] Tdarr_Server - platform_arch_isdocker: linux_x64_docker_false
[2023-04-05T13:40:01.261] [INFO] Tdarr_Server - Preparing environment
[2023-04-05T13:40:02.623] [INFO] Tdarr_Server - Tdarr started.
[2023-04-05T13:40:02.623] [INFO] Tdarr_Server - Tdarr documents folder:/app/server
[2023-04-05T13:40:02.623] [INFO] Tdarr_Server - Checking directories
[2023-04-05T13:40:02.626] [INFO] Tdarr_Server - Tdarr_Server listening at http://0.0.0.0:8266
[2023-04-05T13:40:02.626] [TRACE] Tdarr_Server -
    --------------------------------------------------------------------------
    --------------------------------------------------------------------------

    Tdarr_WebUI running at http://localhost:8265/#/

    --------------------------------------------------------------------------
    --------------------------------------------------------------------------

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:8265/#/' ]
}
[2023-04-05T13:40:02.646] [ERROR] Tdarr_Server - Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:8265/#/' ]
}
[2023-04-05T13:40:02.647] [FATAL] Tdarr_Server - Error in main thread:Error: spawn xdg-open ENOENT
[2023-04-05T13:40:02.687] [INFO] Tdarr_Node - Cloning plugins
[2023-04-05T13:40:02.968] [INFO] Tdarr_Server - Node tdarr-6969f9bb5c-6gnqn [ID=LGySuITJY] [Address=::ffff:127.0.0.1] [PID=204] registered
[2023-04-05T13:40:02.969] [INFO] Tdarr_Node - Node connected & registered
[2023-04-05T13:40:03.259] [INFO] Tdarr_Node - Finished downloading plugins!
[2023-04-05T13:40:03.625] [INFO] Tdarr_Server - Checking binary paths
[2023-04-05T13:40:03.949] [INFO] Tdarr_Server - Running binary tests
[2023-04-05T13:40:04.534] [INFO] Tdarr_Server - ---------------Binary tests start----------------
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - handbrakePath:HandBrakeCLI
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - ffmpegPath:/app/Tdarr_Server/node_modules/ffmpeg-static/ffmpeg
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - mkvpropedit:mkvpropedit
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - Binary test 1: handbrakePath working
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - Binary test 2: ffmpegPath working
[2023-04-05T13:40:04.535] [INFO] Tdarr_Server - Binary test 3: mkvpropeditPath working
[2023-04-05T13:40:04.536] [INFO] Tdarr_Server - ---------------Binary tests end-------------------
[2023-04-05T13:40:04.536] [INFO] Tdarr_Server - Running scanner tests
[2023-04-05T13:40:04.538] [INFO] Tdarr_Server - ---------------Scanner tests start----------------
[2023-04-05T13:40:04.538] [INFO] Tdarr_Server - ffprobePath:/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
[2023-04-05T13:40:04.538] [INFO] Tdarr_Server - ccextractorPath:/app/Tdarr_Server/assets/app/ccextractor/ccextractor
[2023-04-05T13:40:04.538] [INFO] Tdarr_Server - Scanner test: Scanning file start
[2023-04-05T13:40:07.648] [INFO] Tdarr_Node - [4963ms]Plugin update finished
[2023-04-05T13:40:10.183] [INFO] Tdarr_Server - Scanner test: Scanning file end
[2023-04-05T13:40:10.183] [INFO] Tdarr_Server - Scanner test 1: FFprobe working
[2023-04-05T13:40:10.183] [INFO] Tdarr_Server - Scanner test 2: Exiftool working
[2023-04-05T13:40:10.183] [INFO] Tdarr_Server - Scanner test 3: Mediainfo working
[2023-04-05T13:40:10.183] [INFO] Tdarr_Server - Scanner test 4: CCExtractor working
[2023-04-05T13:40:10.184] [INFO] Tdarr_Server - ---------------Scanner tests end----------------
[2023-04-05T13:40:10.185] [INFO] Tdarr_Server - Database has finished initialising
[2023-04-05T13:40:10.304] [INFO] Tdarr_Server - Updating plugins
[2023-04-05T13:40:10.355] [INFO] Tdarr_Server - Job report history size is within limit. Limit:10240 MiB, Size:0 MiB
[2023-04-05T13:40:11.348] [INFO] Tdarr_Server - Cache cleaner start
[2023-04-05T13:40:11.352] [INFO] Tdarr_Server - Cache cleaner end
[2023-04-05T13:40:11.547] [INFO] Tdarr_Server - Cloning plugins
[2023-04-05T13:40:11.974] [INFO] Tdarr_Server - Finished downloading plugins!
[2023-04-05T13:40:15.792] [INFO] Tdarr_Server - [4248ms]Plugin update finished
s6-svwait: fatal: supervisor died
```

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: [e.g. Linux]
 - Version [e.g. 2.00.00]

**Additional context**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2023-04-05T13:13:26Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: automata
    app.kubernetes.io/name: tdarr
    app.kubernetes.io/version: 2.00.20.1
  name: tdarr
  namespace: media
  resourceVersion: "4065655"
  uid: f52bbfc5-7639-4a9d-b250-15d43234d648
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: tdarr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: tdarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "3000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: nodeName
          value: $(POD_NAME)
        - name: internalNode
          value: "true"
        image: ghcr.io/haveagitgat/tdarr:2.00.20.1@sha256:75e128ebb10f769615e5878fc2dad618adbd17a01e3a96060338e28dc8978a1c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tdarr
        ports:
        - containerPort: 8265
          name: http
          protocol: TCP
        - containerPort: 8266
          name: server
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            gpu.intel.com/i915: "1"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/configs
          name: config
        - mountPath: /app/server
          name: server
        - mountPath: /media
          name: media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tdarr-config
      - name: server
        persistentVolumeClaim:
          claimName: tdarr-server
      - name: media
        persistentVolumeClaim:
          claimName: media
status:
  conditions:
  - lastTransitionTime: "2023-04-05T13:13:26Z"
    lastUpdateTime: "2023-04-05T13:43:15Z"
    message: ReplicaSet "tdarr-657fddb464" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-05T13:50:58Z"
    lastUpdateTime: "2023-04-05T13:50:58Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

**Comment by uhthomas** [comment]
@HaveAGitGat I'm using containerd 1.6.18 and have other s6 containers running fine on the same host. I'm not sure that's the problem. Do you have any other ideas?

**Comment by uhthomas** [comment]
Unfortunately I have already tried that. The scheduler will have recreated the container hundreds of times.

**Comment by HaveAGitGat** [comment]
Sorry not too sure then, haven't heard of that error before.

Could try removing the resource limits in your config file.

**Comment by uhthomas** [comment]
Removing resource requests and limits doesn't seem to help either I'm afraid.

**Comment by uhthomas** [comment]
Honestly, I think I'm an idiot. I had copied another manifest as a base template and forgot to remove the health check. I should have checked the pod events. I imagine that Kubernetes was killing the container for failing the incorrect health check. 

I apologise for wasting your time, though I really do appreciate your help. Thank you.

**Comment by HaveAGitGat** [comment]
No worries, we’ve all been there 😅
