### ISSUE TITLE
 Unexpected token u in JSON

### ISSUE THREAD

**Issue by uhthomas** [HaveAGitGat/Tdarr#764]
**Describe the bug**

It looks like there is some unexpected JSON being passed around.

```
[2023-04-07T20:43:08.001] [INFO] Tdarr_Server - Sending 1177 files for extraction
[2023-04-07T20:43:28.993] [ERROR] Tdarr_Server - SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at /snapshot/be/srcug/fileScanners.js:1:18390
at _0x193450 (/snapshot/be/srcug/fileScanners.js:1:4404)
at Object.next (/snapshot/be/srcug/fileScanners.js:1:2632)
at _0x52030b (/snapshot/be/srcug/fileScanners.js:1:1603)
[2023-04-07T20:43:45.475] [WARN] Tdarr_Server - FFprobe was unable to extract any data from this file: /media/movies/Airplane! (1980)/Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso
[2023-04-07T20:43:46.302] [ERROR] Tdarr_Server - SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at /snapshot/be/srcug/fileScanners.js:1:18390
at _0x193450 (/snapshot/be/srcug/fileScanners.js:1:4404)
at Object.next (/snapshot/be/srcug/fileScanners.js:1:2632)
at _0x52030b (/snapshot/be/srcug/fileScanners.js:1:1603)
```

**To Reproduce**

Not sure, sorry.

**Expected behavior**

Probably shouldn't have this error.

**Screenshots**

**Please provide the following information:**
- Config files 
- Log files  
-Worker error 

 - OS: Linux
 - Browser chromium
 - Version 2.00.20.1

**Additional context**

**Comment by HaveAGitGat** [comment]
Are files showing up in the UI?

**Comment by uhthomas** [comment]
Looks like it, though with missing info?

![image](https://user-images.githubusercontent.com/9749173/230678445-b989dc79-435f-4649-bbe0-e578a3dfe2c7.png)

**Comment by uhthomas** [comment]
Looks like it has valid json. I wonder where the error comes from.

```json
{
  "_id": "/media/movies/Airplane! (1980)/Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso",
  "file": "/media/movies/Airplane! (1980)/Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso",
  "DB": "Q_sIyKxrf",
  "footprintId": "8csl-Ldcd",
  "hasClosedCaptions": false,
  "container": "iso",
  "scannerReads": {
    "ffProbeRead": "\"FFprobe was unable to extract any data from this file: /media/movies/Airplane! (1980)/Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso\"",
    "exiftoolRead": "success",
    "mediaInfoRead": "success",
    "closedCaptionRead": "success"
  },
  "ffProbeData": {},
  "file_size": 35688.875,
  "video_resolution": "",
  "fileMedium": "other",
  "video_codec_name": "",
  "audio_codec_name": "",
  "lastPluginDetails": "none",
  "createdAt": 1680901497830,
  "bit_rate": 0,
  "statSync": {
    "dev": 1048825,
    "mode": 33204,
    "nlink": 1,
    "uid": 1000,
    "gid": 2000,
    "rdev": 0,
    "blksize": 4194304,
    "ino": 1099511920574,
    "size": 37422497792,
    "blocks": 73090816,
    "atimeMs": 1611955399000,
    "mtimeMs": 1611955399000,
    "ctimeMs": 1680899614142.3237,
    "birthtimeMs": 1680844188000.7908,
    "atime": "2021-01-29T21:23:19.000Z",
    "mtime": "2021-01-29T21:23:19.000Z",
    "ctime": "2023-04-07T20:33:34.142Z",
    "birthtime": "2023-04-07T05:09:48.001Z"
  },
  "HealthCheck": "",
  "TranscodeDecisionMaker": "",
  "lastHealthCheckDate": 0,
  "holdUntil": 0,
  "lastTranscodeDate": 0,
  "bumped": false,
  "history": "",
  "oldSize": 0,
  "newSize": 0,
  "videoStreamIndex": -1,
  "meta": {
    "SourceFile": "/media/movies/Airplane! (1980)/Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso",
    "errors": [],
    "ExifToolVersion": 12.4,
    "FileName": "Airplane.1980.REMASTERED.COMPLETE.BLURAY-PEGASUS.iso",
    "Directory": "/media/movies/Airplane! (1980)",
    "FileSize": "35 GiB",
    "FileModifyDate": {
      "year": 2021,
      "month": 1,
      "day": 29,
      "hour": 21,
      "minute": 23,
      "second": 19,
      "millisecond": 0,
      "tzoffsetMinutes": 0,
      "rawValue": "2021:01:29 21:23:19+00:00"
    },
    "FileAccessDate": {
      "year": 2021,
      "month": 1,
      "day": 29,
      "hour": 21,
      "minute": 23,
      "second": 19,
      "millisecond": 0,
      "tzoffsetMinutes": 0,
      "rawValue": "2021:01:29 21:23:19+00:00"
    },
    "FileInodeChangeDate": {
      "year": 2023,
      "month": 4,
      "day": 7,
      "hour": 20,
      "minute": 33,
      "second": 34,
      "millisecond": 0,
      "tzoffsetMinutes": 0,
      "rawValue": "2023:04:07 20:33:34+00:00"
    },
    "FilePermissions": "-rw-rw-r--",
    "Error": "File header is all binary zeros"
  },
  "mediaInfo": {
    "@ref": "",
    "track": [
      {
        "@type": "General",
        "VideoCount": "1",
        "Format": "AVC",
        "FileSize": "37422497792",
        "FrameRate": "23.976"
      },
      {
        "@type": "Video",
        "Format": "AVC",
        "Format_Profile": "High",
        "Format_Level": "4.1",
        "Format_Settings_CABAC": "Yes",
        "Format_Settings_GOP": "N=1",
        "Width": "1920",
        "Height": "1080",
        "Stored_Height": "1088",
        "Sampled_Width": "1920",
        "Sampled_Height": "1080",
        "PixelAspectRatio": "1.000",
        "DisplayAspectRatio": "1.778",
        "FrameRate": "23.976",
        "Standard": "NTSC",
        "ColorSpace": "YUV",
        "ChromaSubsampling": "4:2:0",
        "BitDepth": "8",
        "ScanType": "Progressive",
        "colour_description_present": "Yes",
        "colour_description_present_Source": "Stream",
        "colour_range": "Limited",
        "colour_range_Source": "Stream",
        "colour_primaries": "BT.709",
        "colour_primaries_Source": "Stream",
        "transfer_characteristics": "BT.709",
        "transfer_characteristics_Source": "Stream",
        "matrix_coefficients": "BT.709",
        "matrix_coefficients_Source": "Stream"
      }
    ]
  },
  "scanLog": "FFprobe was unable to extract data from this file. It is likely that the file is corrupt else FFprobe can't handle this file."
}
```

**Comment by HaveAGitGat** [comment]
Sounds like a permissions issue as ffprobe can’t read the file.

Can try a sample file:
https://samples.tdarr.io/api/v1/samples/sample__1080__libx264__aac__30s__video.mkv

**Comment by HaveAGitGat** [comment]
Or could just that ffprobe can’t handle that file for some reason

**Comment by uhthomas** [comment]
Possibly the latter, I don't see any permission errors and it only seems to be for a few of them. Just thought it would be good to raise this as there may be something unexpected happening if it's trying to decode a non-json string.

**Comment by HaveAGitGat** [comment]
Ah might be that ffprobe can’t read ISO files so isn’t giving output to parse.

Can check by running ffprobe with these args:
     
      '-v',
      'quiet',
      '-print_format',
      'json',
      '-show_format',
      '-show_streams',
      filepath,

**Comment by HaveAGitGat** [comment]
mediaInfo and exifTool are able to read the file so just seems ffprobe is not able to. Would need to submit a sample to bug report:
https://ffmpeg.org/bugreports.html

**Comment by uhthomas** [comment]
That's fine. Though it seems like there may need to be some change in Tdarr too which checks for the correct exit code or something from ffprobe? It shouldn't be failing to parse JSON strings like that?

**Comment by afurtad0** [comment]
I'm facing the same problem but on an additional node.
I have an lxc container running the server and node and another lxc container running just the node, both containers have the paths configured in the same way but only the primary container can transcode. The additional node shows the error "Unexpected token u in JSON" when starting the ffmpeg flow.

**Comment by tomerh2001** [comment]
Any solution? Why is this closed?

**Comment by sstratoti** [comment]
Are the PUID and GUID set correctly in the env vars? Mine were incorrect in my docker compose. Once corrected, it ran fine.

**Comment by tomerh2001** [comment]
> Are the PUID and GUID set correctly in the env vars? Mine were incorrect in my docker compose. Once corrected, it ran fine.

Correct for what? I get this error for only 1/5 of my library, the rest works...

**Comment by sstratoti** [comment]
I read on Reddit that this could be a permissions issue. If the TDarr node (which could be on another server accessing through mapped network shares) cannot read the original file or write to the shared temp directory, it may cause this error.
