### ISSUE TITLE
Git clone fails (tdarr_aio)

### ISSUE THREAD

**Issue by theg00s3** [HaveAGitGat/Tdarr#78]
When I run the default command, I get this:

Cloning plugins
Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/git-clone/index.js:33:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
Error: ENOENT: no such file or directory, stat '/home/Tdarr/Documents/Tdarr/Plugins/temp/Community'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/graceful-fs/polyfills.js:308:16)
    at getStatsSync (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/fs-extra/lib/util/stat.js:60:18)
    at Object.checkPathsSync (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.copySync (/home/Tdarr/Tdarr/bundle/programs/server/npm/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at server/main.js:805:17
    at runWithEnvironment (packages/meteor.js:1286:24)
Plugin update finished

and it hangs afterwards.
I've tried deleting the docker volume and the config folder, but nothing has worked

**Comment by HaveAGitGat** [comment]
Have you made sure this path exists where you mapped your Tdarr documents folder?

> /home/Tdarr/Documents/Tdarr/Plugins/temp/Community

Else it could be a write permissions issue.

**Comment by theg00s3** [comment]
I've tried creating the folder, running the docker container seems to delete it. The permissions are 777 (yes I shouldn't do this but I had to try)

**Comment by theg00s3** [comment]
I don't know what the underlying issue was, but deleting the tdarr folder, the docker volume and the container then restarting has fixed it.

**Comment by HaveAGitGat** [comment]
Pleased to hear its resolved.
