### ISSUE TITLE
Transport error - Tdarr node suddenly is unable to register/connect to tdarr server

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#810]
**Describe the bug**
Suddenly Tdarr node is unable to connect to or register with tdarr server.

**To Reproduce**
Start the Tdarr server, and wait for chmod to finish. Start Tdarr node. Observer error in Tdarr_Server_Log.txt

**Expected behavior**
I expected the Tdarr node to be able to communicate with and connect to the Tdarr server like it has for the past year or so.

Relevant section of logfile:

```
[2023-07-17T06:50:50.710] [INFO] Tdarr_Node - /app/configs/Tdarr_Node_Config.json
[2023-07-17T06:50:50.821] [INFO] Tdarr_Node - {
  nodeID: 'JLsai2Hxo',
  nodeName: 'Earth',
  serverIP: '192.168.86.31',
  serverPort: '8266',
  handbrakePath: '',
  ffmpegPath: '',
  mkvpropeditPath: '',
  pathTranslators: [ { server: '', node: '' } ],
  logLevel: 'INFO',
  priority: -1,
  platform_arch_isdocker: 'linux_x64_docker_true',
  processPid: 192,
  platform_arch: 'linux_x64_docker_true',
  nodeIP: '192.168.86.26',
  nodePort: '8268'
}
[2023-07-17T06:50:50.869] [INFO] Tdarr_Node - version: 2.00.21
[2023-07-17T06:50:50.869] [INFO] Tdarr_Node - platform_arch_isdocker: linux_x64_docker_true
[2023-07-17T06:50:50.870] [INFO] Tdarr_Node - Starting Tdarr_Node
[2023-07-17T06:50:50.870] [INFO] Tdarr_Node - Preparing environment
[2023-07-17T06:50:50.871] [INFO] Tdarr_Node - Updating plugins
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - handbrakePath:HandBrakeCLI
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - ffmpegPath:tdarr-ffmpeg
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - Binary test 1: handbrakePath working
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - Binary test 3: mkvpropeditPath working
[2023-07-17T06:50:51.016] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-07-17T06:50:53.939] [ERROR] Tdarr_Node - Failed to contact server, retrying...
[2023-07-17T06:50:53.939] [ERROR] Tdarr_Node - Node connection error to :192.168.86.31:8266
[2023-07-17T06:50:53.939] [ERROR] Tdarr_Node - TransportError: xhr poll error
    at Polling.onError (/snapshot/node/node_modules/engine.io-client/build/cjs/transport.js:45:37)
    at Request.<anonymous> (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:251:18)
    at Request.<anonymous> (/snapshot/node/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:352:14)
    at Timeout._onTimeout (/snapshot/node/node_modules/engine.io-client/build/cjs/transports/polling.js:325:30)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  description: 0,
  context: XMLHttpRequest {
    UNSENT: 0,
    OPENED: 1,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    DONE: 4,
    readyState: 4,
    onreadystatechange: [Function (anonymous)],
    responseText: 'Error: connect EHOSTUNREACH 192.168.86.31:8266\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)',
    responseXML: '',
    status: 0,
    statusText: Error: connect EHOSTUNREACH 192.168.86.31:8266
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -113,
      code: 'EHOSTUNREACH',
      syscall: 'connect',
      address: '192.168.86.31',
      port: 8266
    },
    open: [Function (anonymous)],
    setDisableHeaderCheck: [Function (anonymous)],
    setRequestHeader: [Function (anonymous)],
    getResponseHeader: [Function (anonymous)],
    getAllResponseHeaders: [Function (anonymous)],
    getRequestHeader: [Function (anonymous)],
    send: [Function (anonymous)],
    handleError: [Function (anonymous)],
    abort: [Function (anonymous)],
    addEventListener: [Function (anonymous)],
    removeEventListener: [Function (anonymous)],
    dispatchEvent: [Function (anonymous)]
  },
  type: 'TransportError'
}
```
[Tdarr_Server_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12070245/Tdarr_Server_Log.txt)
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12070248/Tdarr_Node_Log.txt)

 - OS: Docker container running on Synology
 - Version 2.00.21

**Comment by adefaria** [comment]
Ah, some more data. I run Tdarr Server on my Synology and I run Tdarr nodes on my System76 Desktop and a MacBook on which I installed Ubuntu. Generally, I only run one Tdarr node on my desktop since it has an Nvidia card and I have yet to figure out how to get Tdarr to use the GPU on the Macbook. 

For kicks, I started the Docker container on my Macbook Ubuntu machine and it registered and tried to transcode recent files but failed for various reasons (probably because it's not set up correctly - hmmm... actually because my tdarr configuration says "Use the GPUs" and it complains about not being able to use the Nvidia GPUs - my Macbook doesn't have an Nvidia card). Looking at the logs I pulled out the failing ffmpeg command and ran it on my desktop. Ran OK.

Next "trick": I did a docker exec -it tdarr_node bash on my desktop to enter my docker container. Next, I took a tdarr-ffmpeg command out of one of the failing transcodes on my Macbook and pasted that command into the docker container. Transcoded fine. So then the problem doesn't seem to be with the container or its ability to transcode - just its ability to talk to the server.

(BTW I noticed that filenames in that ffmpeg command are now protected with quotes! Thanks, man!)

**Comment by pinpspinps** [comment]
Hello, 
I encounter exactly the same issue with Tdarr in docker on raspberry pi 4.

**Comment by adefaria** [comment]
Hmmm... Today it started working again. Odd.

AFAICT I didn't do anything different. I have a bash script that removes the container, pulls the image if necessary, and then does a docker run to restart the container. I had run that and it never registered. This script does a similar thing on my Macbook but doesn't enable the Nvidia stuff because my Macbook doesn't have an Nvidia card. But my current plugin setup for Tdarr Server uses GPU and Nivida stuff and fails on the Macbook. But I did see that the Macbook registered as the desktop still failed to register, Today I noticed the Macbook's docker container was still running so I stopped that. Then I decided to try a simple docker start tdarr_node on my desktop and it came up and registered! Odd.

**Comment by adefaria** [comment]
Hmmm... Today it started working again. Odd.

AFAICT I didn't do anything different. I have a bash script that removes the container, pulls the image if necessary, and then does a docker run to restart the container. I had run that and it never registered. This script does a similar thing on my Macbook but doesn't enable the Nvidia stuff because my Macbook doesn't have an Nvidia card. But my current plugin setup for Tdarr Server uses GPU and Nivida stuff and fails on the Macbook. But I did see that the Macbook registered as the desktop still failed to register, Today I noticed the Macbook's docker container was still running so I stopped that. Then I decided to try a simple docker start tdarr_node on my desktop and it came up and registered! Odd.

**Comment by wnypoker** [comment]
Getting the same error with a node on OSX I just setup.  PC nodes work fine.

error:
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - ---------------Binary tests start----------------
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - handbrakePath:/usr/local/bin/HandBrakeCLI
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - ffmpegPath:/Users/userx/tdarr/Tdarr_Node/node_modules/ffmpeg-static/ffmpeg
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - mkvpropedit:mkvpropedit
[2023-12-29T08:31:54.300] [ERROR] Tdarr_Node - Binary test 1: handbrakePath not working
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - Binary test 2: ffmpegPath working
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - Binary test 3: mkvpropeditPath working
[2023-12-29T08:31:54.300] [INFO] Tdarr_Node - ---------------Binary tests end-------------------
[2023-12-29T08:31:54.791] [ERROR] Tdarr_Node - Node connection error to: 0.0.0.0:8266
[2023-12-29T08:31:54.791] [ERROR] Tdarr_Node - TransportError: xhr poll error
    at Polling.onError (/Users/userx/tdarr/Tdarr_Node/node_modules/engine.io-client/build/cjs/transport.js:45:37)
    at Request.<anonymous> (/Users/userx/tdarr/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:251:18)
    at Emitter.emit (/Users/userx/tdarr/Tdarr_Node/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/Users/userx/tdarr/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:352:14)
    at Timeout._onTimeout (/Users/userx/tdarr/Tdarr_Node/node_modules/engine.io-client/build/cjs/transports/polling.js:325:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  description: 0,
  context: XMLHttpRequest {
    UNSENT: 0,
    OPENED: 1,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    DONE: 4,
    readyState: 4,
    onreadystatechange: [Function (anonymous)],
    responseText: 'Error: connect ECONNREFUSED 0.0.0.0:8266\n' +
      '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)',
    responseXML: '',
    status: 0,
    statusText: Error: connect ECONNREFUSED 0.0.0.0:8266
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '0.0.0.0',
      port: 8266
    },

----

what is strange is that I know I set the IP address of the server and the node in the node config.

{
  "nodeID": "mac1",
  "nodeName": "mac1",
  "serverIP": "192.168.0.4",
....

  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "platform_arch": "darwin_arm64_docker_false",
  "nodeIP": "192.168.0.3",
  "nodePort": "8267"
}

**Comment by supersnellehenk** [comment]
@wnypoker your json is probably invalid, try running your node config json through a JSON validator.

**Comment by wnypoker** [comment]
That was the issue.  My sincere apologies and thanks.

**Comment by crypto-coder-314** [comment]
I just faced the same problem and the solution was very simple.

I had 100 files in the staging session, making it full. No other files were processed because of this, and the node was getting the same errors indicated in this issue.
By accepting the files (and waiting a long time for them to process), the problem was solved.
