### ISSUE TITLE
tdarr node worked disconnected pruning

### ISSUE THREAD

**Issue by picarica** [HaveAGitGat/Tdarr#833]
**Describe the bug**
my tdarr node that runs on plain linux remotely is failing

**To Reproduce**
on my PC i have tdarr WEB ui + internal node in docker, on seperate linux machine i have tdarr node installed without docker, i have media mounted in docker and also via sshfs in the remote server, library is set  and cache in the same sshfs mount, but i still get these fails 
```

[2023-08-28T06:45:33.966] [ERROR] Tdarr_Node - Worker any-aphid exited with code 1 and signal null
TypeError: worker2[W(...)] is not a functiontall printInstalled
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:39.434] [FATAL] Tdarr_Node - TypeError: worker2[W(...)] is not a function
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:39.466] [ERROR] Tdarr_Node - Worker lame-lion exited with code 1 and signal null
TypeError: worker2[W(...)] is not a functiontall printInstalled
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:39.788] [FATAL] Tdarr_Node - TypeError: worker2[W(...)] is not a function
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:39.825] [ERROR] Tdarr_Node - Worker neat-nag exited with code 1 and signal null
[2023-08-28T06:45:39.940] [ERROR] Tdarr_Node - Worker kind-kid disconnected. Pruning.
TypeError: worker2[W(...)] is not a functiontall printInstalled
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:41.623] [FATAL] Tdarr_Node - TypeError: worker2[W(...)] is not a function
    at ChildProcess.<anonymous> (/home/bucek/Tdarr_Node/srcug/workers/worker1.js:1:19274)
    at ChildProcess.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[2023-08-28T06:45:41.661] [ERROR] Tdarr_Node - Worker that-thrip exited with code 1 and signal null

```

internal node works as expected
**Expected behavior**
tdarr correctly does the work

**Screenshots**
![Screenshot from 2023-08-28 08-49-33](https://github.com/HaveAGitGat/Tdarr/assets/45492894/29ec38af-ce21-4c45-aea3-6a31d25d699a)
here is screen from report of one of the failed files from the node sshfs mount is /media

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Config.txt](https://github.com/HaveAGitGat/Tdarr/files/12451159/Tdarr_Node_Config.txt)

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12451166/Tdarr_Node_Log.txt)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
put it in the screenshot section
 - OS: ubuntu server 22.04 (docker is in linux mint)
 - Browser chromium
 - Version: node 2.10.01, docker latest tag recently pulled

**Additional context**

**Comment by HaveAGitGat** [comment]
Have you tried unpacking the the non-docker linux node again? Could be that one of the files failed to unpack or was interrupted during unpack so would recommend trying that.

**Comment by picarica** [comment]
> Have you tried unpacking the the non-docker linux node again? Could be that one of the files failed to unpack or was interrupted during unpack so would recommend trying that.

tried it out, but now it cant even download plugins, before it worked fine, did the update break it ?
![Screenshot from 2023-08-28 10-39-43](https://github.com/HaveAGitGat/Tdarr/assets/45492894/84cc0240-c89e-411f-9256-313e3b2e5d47)

**Comment by HaveAGitGat** [comment]
Just unpacked on `Ubuntu 20.04.6 LTS` and it working fine for me:
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/49c5f7bb-2a57-4ec7-a7fc-92d3a8bc7e32)

No errors: 
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/58bbfee2-4722-4324-8e7d-379e11268234)

From your log it seems plugins have downloaded fine (says it took 4180ms). Then it's installed some plugin dependencies like import-fresh. Not sure what this is, does `srcug/workers/worker2.js` exist?

**Comment by picarica** [comment]
[Tdarr_Node_Log.txt](https://github.com/HaveAGitGat/Tdarr/files/12453309/Tdarr_Node_Log.txt)
ill try uploading this newest log file, but i confirmed scrug worker2.js exists
but not sure if i metnioned, i installed it week ako this setup, i updated it with the Tdarr_updater yesterday not working since

**Comment by HaveAGitGat** [comment]
Yeah it's a strange issue as I've not had anyone mention this to me yet and it's working fine in the tests, in docker, on my local windows/ubuntu system etc so not too sure. 

You can try downloading directly from here and unzipping it yourself:
https://f000.backblazeb2.com/file/tdarrs/versions.json

You can also try downgrading and I'll leave this open in case anyone else has the issue:
https://docs.tdarr.io/docs/releases/changing-version

**Comment by picarica** [comment]
downgrading to last major version fix it, btw

**Comment by HaveAGitGat** [comment]
Please try 2.10.02 just released, reopen if needed thanks.
