### ISSUE TITLE
Flow Check Video Bitrate Not Finding Bitrate

### ISSUE THREAD

**Issue by ohsnapword** [HaveAGitGat/Tdarr#846]
**Describe the bug**
The Check Video Bitrate flow plugin is not able to find the video bitrate of MKV files.

**To Reproduce**
Create a flow with following plugins:
- Input File
- Run MKVPropEdit
- Check Video Bitrate

**Expected behavior**
Plugin is able to find video bitrate and take action.

**Screenshots**

**Please provide the following information:**

2023-09-09T05:45:03.688Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:[Step W03] [C8] [Convert to MKV HEVC] Running plugin: 1.0.0: checkVideoBitrate: Bitrate > 30mpbs?

2

2023-09-09T05:45:03.701Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Scanning original library file

3

2023-09-09T05:45:03.704Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:{

4

2023-09-09T05:45:03.704Z "exifToolScan": true,

5

2023-09-09T05:45:03.704Z "mediaInfoScan": false,

6

2023-09-09T05:45:03.704Z "closedCaptionScan": false

7

2023-09-09T05:45:03.704Z }

8

2023-09-09T05:45:03.706Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Loading source file: /FreenasMedia/Classic Cartoons/Looney Tunes/Season 1968/Looney Tunes (1929) - S1968E02 - [DVD] [8-bit].mkv

9

2023-09-09T05:45:03.711Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Scanning source file: /FreenasMedia/Classic Cartoons/Looney Tunes/Season 1968/Looney Tunes (1929) - S1968E02 - [DVD] [8-bit].mkv

10

2023-09-09T05:45:03.729Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Scan types: {

11

2023-09-09T05:45:03.729Z "exifToolScan": true,

12

2023-09-09T05:45:03.729Z "mediaInfoScan": false,

13

2023-09-09T05:45:03.729Z "closedCaptionScan": false

14

2023-09-09T05:45:03.729Z }

15

2023-09-09T05:45:03.734Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Scanning file

16

2023-09-09T05:45:03.741Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Requesting Tdarr Server to scan file

17

2023-09-09T05:45:04.911Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Scan complete

18

2023-09-09T05:45:04.912Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Source file scan complete

19

2023-09-09T05:45:04.912Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Loaded plugin inputs: {

20

2023-09-09T05:45:04.912Z "unit": "kbps",

21

2023-09-09T05:45:04.912Z "greaterThan": "0",

22

2023-09-09T05:45:04.912Z "lessThan": "30000"

23

2023-09-09T05:45:04.912Z }

24

2023-09-09T05:45:04.914Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:[-error-]

25

2023-09-09T05:45:04.918Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Error: Video bitrate not found

26

2023-09-09T05:45:04.923Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:"Video bitrate not found"

27

2023-09-09T05:45:04.930Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:"Error: Video bitrate not found\n at Object.plugin (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/video/checkVideoBitrate/1.0.0/index.js:94:15)\n at a.<anonymous> (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:16452)\n at k (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:2328)\n at Object.next (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:1415)\n at h (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:867)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

28

2023-09-09T05:45:04.935Z LxhT2uET07c:Node[Internal Node]:Worker[knobby-koi]:Flow has failed and flow variable flowFailed !== true, running On Flow Fail plugin

 - OS: TrueNAS Scale 22.12.2
 - Browser: Edge
 - Version: 2.11.01

**Additional context**
TDarr is running in Docker container.

**Comment by ohsnapword** [comment]
I tested the flow with an MP4 file and got the same error.

**Comment by AroundThisWorldAgain** [comment]
Same error.  FYI this is caused by `mediaInfo` being an empty object in the file data:

    "mediaInfo": {}

I have `MediaInfo` on in the library, but the log shows:

    "mediaInfoScan": false,

`ffProbeData.streams` does have the necessary data, fwiw.

**Comment by mguffin68** [comment]
Same issue here, 2.11.01 running on unraid.

22

2023-09-16T09:51:35.436Z S9L0jde6c:Node[unraid-node]:Worker[equal-elk]:Error: Video bitrate not found

23

2023-09-16T09:51:35.436Z S9L0jde6c:Node[unraid-node]:Worker[equal-elk]:"Video bitrate not found"

24

2023-09-16T09:51:35.437Z S9L0jde6c:Node[unraid-node]:Worker[equal-elk]:"Error: Video bitrate not found\n at Object.plugin (/app/Tdarr_Node/assets/app/plugins/FlowPlugins/CommunityFlowPlugins/video/checkVideoBitrate/1.0.0/index.js:94:15)\n at a.<anonymous> (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:16452)\n at k (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:2328)\n at Object.next (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:1415)\n at h (/app/Tdarr_Node/srcug/workers/workerFlowPlugin.js:1:867)"

25

2023-09-16T09:51:35.438Z S9L0jde6c:Node[unraid-node]:Worker[equal-elk]:Flow has failed

**Comment by HaveAGitGat** [comment]
More info on this here but will release an update which should help with this:
https://github.com/HaveAGitGat/Tdarr_Plugins/issues/460

**Comment by HaveAGitGat** [comment]
2.12.01 released, added some improvements so should be working as expected
