### ISSUE TITLE
Tdarr_Plugin_a9hf_New_file_duration_check  does not work under Flows

### ISSUE THREAD

**Issue by Kedryn** [HaveAGitGat/Tdarr#857]
**Describe the bug**
The legacy Tdarr_Plugin_a9hf_New_file_duration_check does not work under Flows
it  always reads a duration of 0 from original file.

**To Reproduce**

[Z17YC-JtlI-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12706467/Z17YC-JtlI-log.txt)

```2023-09-23T04:23:47.792Z Z17YC-JtlI:Node[syneto-hy]:Worker[vast-vireo]:[-error-]
2023-09-23T04:23:47.793Z Z17YC-JtlI:Node[syneto-hy]:Worker[vast-vireo]:Error: New file duration not within limits. New file has duration 4833 s which is Infinity% of original file duration:  0 s. upperBound is 101%
2023-09-23T04:23:47.795Z Z17YC-JtlI:Node[syneto-hy]:Worker[vast-vireo]:"New file duration not within limits. New file has duration 4833 s which is Infinity% of original file duration:  0 s. upperBound is 101%"
2023-09-23T04:23:47.797Z Z17YC-JtlI:Node[syneto-hy]:Worker[vast-vireo]:"Error: New file duration not within limits. New file has duration 4833 s which is Infinity% of original file duration:  0 s. upperBound is 101%\n    at Object.plugin (C:\\Users\\Marco\\Desktop\\Tdarr\\Tdarr_Node\\assets\\app\\plugins\\Local\\Tdarr_Plugin_a9hf_New_file_duration_check.js:78:11)\n    at C:\\Users\\Marco\\Desktop\\Tdarr\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\FlowHelpers\\1.0.0\\classicPlugins.js:126:52\n    at step (C:\\Users\\Marco\\Desktop\\Tdarr\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\FlowHelpers\\1.0.0\\classicPlugins.js:33:23)\n    at Object.next (C:\\Users\\Marco\\Desktop\\Tdarr\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\FlowHelpers\\1.0.0\\classicPlugins.js:14:53)\n    at fulfilled (C:\\Users\\Marco\\Desktop\\Tdarr\\Tdarr_Node\\assets\\app\\plugins\\FlowPlugins\\FlowHelpers\\1.0.0\\classicPlugins.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

**Comment by HaveAGitGat** [comment]
Thanks fixed here: https://github.com/HaveAGitGat/Tdarr_Plugins/pull/475

Update plugins on the plugins tab and should work fine.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/447ab2c6-6163-4fa2-a42e-d7da44b0ffc1)
