### ISSUE TITLE
Copying keeps failing with a permission error.

### ISSUE THREAD

**Issue by tobinstultiens** [HaveAGitGat/Tdarr#858]
**Describe the bug**
In the latest version whenever the transcode completes and it attempts to copy it to the directory it will fail with an Erno error about the permissions.

**To Reproduce**
Setup a library to transcode for my setyp I used qsv 

**Expected behavior**
I expected the files to be moved.

**Please provide the following information:**
- Config files  Does not show any error.

- Log files Does not show any error.

-Worker error 

<details>
<summary>Logs</summary>

2023-09-24T19:50:23.034Z uG5WIE8eqRL:Attempting move from /temp/{video}.mkv to /media/{video}.mkv

2023-09-24T19:50:23.034Z uG5WIE8eqRL:File move error: {"errno":-18,"code":"EXDEV","syscall":"rename","path":"/temp/{video}.mkv","dest":"/media/{video}.mkv"}

2023-09-24T19:50:23.034Z uG5WIE8eqRL:Attempting copy from /temp/{video}.mkv to /media/{video}mkv

2023-09-24T19:50:23.035Z uG5WIE8eqRL:File copy error: {"errno":-1,"code":"EPERM","syscall":"copyfile","path":"/temp/{video}.mkv","dest":"/media/{video}.mkv"}

2023-09-24T19:50:23.035Z uG5WIE8eqRL:Error occured when copying cache file

2023-09-24T19:50:23.035Z uG5WIE8eqRL:After copy, cache file of size 235219001 does not match destination file of size 0

</details>

 - OS: Arch
 - Browser Firefox
 - Version [2.12.01](https://hub.docker.com/layers/haveagitgat/tdarr/2.12.01/images/sha256-98680cf40516e2ee2596da99d7c4dad74a417f6afd4ea7a5fce3592995adc7cf?context=explore)

**Comment by tobinstultiens** [comment]
I was able to temporarily resolve the issue by reverting to a previous version. in this case 2.11.01

**Comment by HaveAGitGat** [comment]
Hi, someone else mentioned they had the same issue and was due to the user:group being different on the server and node. Not sure why it would work on the previous version in that case but will look into it thanks.

**Comment by tobinstultiens** [comment]
Strange, since they have always been the same for me since they're both on the same server and using the same user / group.

**Comment by astenger** [comment]
Same problem.
File move error: {"errno":-18,"code":"EXDEV","syscall":"rename",...
my /temp is on a separate nfs mount compared to the library
the error hints at not liking to do this rename across devices

revert to 2.11.01 remediated the issue - thanks @tobinstultiens tobinstultiens

**Comment by HaveAGitGat** [comment]
Thanks does anyone have a the end of a job report comparing 2.11.01 and 2.12.01 so I can check the details on the copy/move section?

**Comment by astenger** [comment]
@HaveAGitGat thanks for looking into this.
Here is a job report that started on 2.12.01. I did multiple re-attempts on the copy that failed since I initially though that it was a perms issue on the NFS server. The final copy/re-attempt at the end is with the downgraded version 2.11.01 which worked.
[bFKYO6v9Wr5-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12773348/bFKYO6v9Wr5-log.txt)
I changed from:
ghcr.io/haveagitgat/tdarr:latest
ghcr.io/haveagitgat/tdarr_node:latest
to
ghcr.io/haveagitgat/tdarr:2.11.01
ghcr.io/haveagitgat/tdarr_node:2.11.01
The problem affected tdarr and tdarr_node and the downgrade worked on both.
I am not sure what you are using to move the files out of temp. Maybe the default behaviour of that tool/syscall changed to not allow cross file system moves. (I have seen a similar issue in something completely else when moving from soft links to hard links.)
Much obliged and love your work!

**Comment by astenger** [comment]
I have been about this a little more without digging into the code:
**if** /temp and the media folder are actually on the same file system doing a hard link instead of a copy is actually a very good performance optimisation that skips a **ton** of io. hardlink the target, unlink the source means one inode created, one deleted and no data touched. 
e.g. standard cp does support option --reflink=always which will use that approach where underlying copy-on-write file systems support that. However, --reflink=always fails with operations across file systems. --reflink=auto would try to do the light weight option first and do a full copy if that does not work.
Hope this might help!

**Comment by HaveAGitGat** [comment]
Thanks can you please try this image:

tdarr_acc:dev_2.12.01_2023_09_30T18_26_19z

**Comment by astenger** [comment]
I don't seem to have access to the image even after logging in:

docker@tdarr0:tdarr $ cat docker-compose.yml | grep acc
    image: tdarr_acc:dev_2.12.01_2023_09_30T18_26_19z

docker@tdarr0:tdarr $ dc up -d
[+] Running 1/1
 ✘ tdarr Error                                                                                                                                                                2.8s
Error response from daemon: pull access denied for tdarr_acc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by HaveAGitGat** [comment]
It’s here fully public:

https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev_2.12.01_2023_09_30T18_26_19z/images/sha256-67e311117445817128f318d98d81e8d465f431d4689293ec8eb5a2afbeb660c3?context=explore

**Comment by simonlock** [comment]
Hi HaveAGitGat,

Since the last update, I too have had tdarr failing every time it attempted to copy files. As a test, I have just now switched to your image provided above and all seems to be working again. Files are being copied successfully.

I've provided below snippets from docker logs for both the tdarr server and tdarr client node.

server logs:

[2023-10-01T10:26:45.599] [ERROR] Tdarr_Server - Error verifying key
[2023-10-01T10:26:45.599] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'trim')
    at /app/Tdarr_Server/srcug/auth.js:1:4362
    at k (/app/Tdarr_Server/srcug/auth.js:1:2075)
    at Object.next (/app/Tdarr_Server/srcug/auth.js:1:1108)
    at h (/app/Tdarr_Server/srcug/auth.js:1:559)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


client node logs:

[2023-10-01T10:31:19.638] [ERROR] Tdarr_Server - Error verifying key
[2023-10-01T10:31:19.639] [ERROR] Tdarr_Server - TypeError: Cannot read properties of undefined (reading 'trim')
    at /app/Tdarr_Server/srcug/auth.js:1:4362
    at k (/app/Tdarr_Server/srcug/auth.js:1:2075)
    at Object.next (/app/Tdarr_Server/srcug/auth.js:1:1108)
    at h (/app/Tdarr_Server/srcug/auth.js:1:559)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-10-01T10:31:20.633] [INFO] Tdarr_Server - Checking binary paths
[2023-10-01T10:31:20.717] [INFO] Tdarr_Server - Running binary tests
[2023-10-01T10:31:21.150] [INFO] Tdarr_Node - verbose:Launching worker
[2023-10-01T10:31:21.172] [INFO] Tdarr_Node - verbose:Worker firm-flea launched
[2023-10-01T10:31:21.249] [INFO] Tdarr_Server - ---------------Binary tests start----------------
[2023-10-01T10:31:21.250] [INFO] Tdarr_Server - handbrakePath:HandBrakeCLI
[2023-10-01T10:31:21.250] [INFO] Tdarr_Server - ffmpegPath:tdarr-ffmpeg
[2023-10-01T10:31:21.251] [INFO] Tdarr_Server - mkvpropedit:mkvpropedit
[2023-10-01T10:31:21.252] [INFO] Tdarr_Server - Binary test 1: handbrakePath working
[2023-10-01T10:31:21.252] [INFO] Tdarr_Server - Binary test 2: ffmpegPath working
[2023-10-01T10:31:21.253] [INFO] Tdarr_Server - Binary test 3: mkvpropeditPath working
[2023-10-01T10:31:21.253] [INFO] Tdarr_Server - ---------------Binary tests end-------------------
[2023-10-01T10:31:21.254] [INFO] Tdarr_Server - Running scanner tests
[2023-10-01T10:31:21.257] [INFO] Tdarr_Server - ---------------Scanner tests start----------------
[2023-10-01T10:31:21.257] [INFO] Tdarr_Server - ffprobePath:/app/Tdarr_Server/node_modules/@ffprobe-installer/linux-x64/ffprobe
[2023-10-01T10:31:21.258] [INFO] Tdarr_Server - ccextractorPath:ccextractor
[2023-10-01T10:31:21.259] [INFO] Tdarr_Server - Scanner test: Scanning file start
[2023-10-01T10:31:22.398] [INFO] Tdarr_Node - verbose:Item request received
[2023-10-01T10:31:22.399] [INFO] Tdarr_Node - verbose:Getting new task
[2023-10-01T10:31:24.337] [WARN] Tdarr_Node - Dependency not found: import-fresh at /app/Tdarr_Node/assets/app/plugins/node_modules/import-fresh
[2023-10-01T10:31:24.342] [INFO] Tdarr_Node - Installing plugin dependency:import-fresh
[2023-10-01T10:31:24.430] [INFO] Tdarr_Server - Scanner test: Scanning file end
[2023-10-01T10:31:24.431] [INFO] Tdarr_Server - Scanner test 1: FFprobe working
[2023-10-01T10:31:24.432] [INFO] Tdarr_Server - Scanner test 2: Exiftool working
[2023-10-01T10:31:24.432] [INFO] Tdarr_Server - Scanner test 3: Mediainfo working
[2023-10-01T10:31:24.433] [INFO] Tdarr_Server - Scanner test 4: CCExtractor working
[2023-10-01T10:31:24.434] [INFO] Tdarr_Server - ---------------Scanner tests end----------------
[2023-10-01T10:31:24.438] [INFO] Tdarr_Server - Database has finished initialising
[2023-10-01T10:31:24.510] [INFO] Tdarr_Server - Updating plugins
[2023-10-01T10:31:24.695] [INFO] Tdarr_Server - Job report history size is within limit. Limit:10240 MiB, Size:0 MiB
[2023-10-01T10:31:24.697] [INFO] Tdarr_Server - Cleaning empty job report folders
[2023-10-01T10:31:25.554] [INFO] Tdarr_Server - Cloning plugins
[2023-10-01T10:31:25.644] [INFO] Tdarr_Server - Cache cleaner start
[2023-10-01T10:31:25.648] [INFO] Tdarr_Server - Cache cleaner end
[2023-10-01T10:31:25.654] [INFO] Tdarr_Node - verbose:Launching worker
[2023-10-01T10:31:25.667] [INFO] Tdarr_Node - verbose:Worker kindly-kob launched
[2023-10-01T10:31:26.242] [INFO] Tdarr_Server - Finished downloading plugins!
npm WARN saveError ENOENT: no such file or directory, open '/app/Tdarr_Node/assets/app/plugins/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/app/Tdarr_Node/assets/app/plugins/package.json'
npm WARN plugins No description
npm WARN plugins No repository field.
npm WARN plugins No README data
npm WARN plugins No license field.

+ import-fresh@3.3.0
added 4 packages from 1 contributor and audited 4 packages in 1.509s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by HaveAGitGat** [comment]
Hi thanks for the info.

FYI those are the wrong logs, are you able to provide the job report log which contains the logs on the copy/move operation at the end:

https://docs.tdarr.io/docs/other/job-reports
 
 Ty

**Comment by simonlock** [comment]
[zEu-4LUMBd-log.txt](https://github.com/HaveAGitGat/Tdarr/files/12777013/zEu-4LUMBd-log.txt)

Hi Please,
Find attached a sample log.

Thanks

**Comment by HaveAGitGat** [comment]
Hi thanks but that appears to be a transcode error log so it doesn’t include the new file cache copy/move operations at the end.

**Comment by HaveAGitGat** [comment]
Woops sorry seems to be fine, phone opened a different log. 

Thanks I’ll release the update today.

This doesn’t seem to be anything to do with permissions but for some reason the native NodeJS copy operation gives a permissions error in your setups which is odd.

**Comment by simonlock** [comment]
It was taken from Transcode: Success/Not required, and the file was successfully transcoded and moved.

**Comment by HaveAGitGat** [comment]
2.13.01 released

**Comment by astenger** [comment]
New release works beautifully.
Much appreciated!

**Comment by HaveAGitGat** [comment]
Great 🙂

**Comment by janerjak** [comment]
Hey, sorry to revive this issue, but I'm having this exact problem using the---at the time of writing---latest version 2.15.01.

I'm running Tdarr as a Docker container on TrueNAS Scale. For transcoding I use Flows.

My /temp is on a different dataset than the destination, so when replacing the original file (or moving the transcoded file to the original directory) first an EXDEV-error occurs (which is to be expected). Attempt #2 (copy, then delete old file) however fails with (-1) EPERM (permission error). However, I'm very sure the permissions are set correctly.

For testing purposes, I tried to encode videos in a temporary Docker host volume /temp-tdarr. The transcode cache directory is located at /temp (still different host device). I set up the Docker environment variables PUID and PGID to the same as my shell user that owns both the host-volumes mapped to /temp and /temp-tdarr. /temp and /temp-tdarr have permissions 777. It still fails with EPERM. Running the copy command on leftover transcodes from /temp to /temp-tdarr directly from shell does not yield an error.
Interestingly, when using remote Tdarr nodes with path translators that map to Samba-Shares of /temp and /temp-tdarr, no issues occur. I'm authenticating in Samba with the same user that the Docker container is running as.

Tdarr can clearly read the source files in /media or /temp-tdarr and write to /temp. Writing to /media or /temp-tdarr should be possible according to UNIX permissions and ACL.

See the relevant excerpt from one of my flows, where I use the "Move to Original Directory" plugin:
```
2023-11-13T19:24:17.579Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:[Step W03] [C10] [HEVC Main10 Slow RF23 Lectures Opus Configurable] Running Community plugin: 1.0.0: replaceOriginalFile: Replace Original File 
2023-11-13T19:24:17.580Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Scanning original library file
2023-11-13T19:24:17.580Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:{
2023-11-13T19:24:17.580Z   "exifToolScan": true,
2023-11-13T19:24:17.580Z   "mediaInfoScan": false,
2023-11-13T19:24:17.580Z   "closedCaptionScan": false
2023-11-13T19:24:17.580Z }
2023-11-13T19:24:17.581Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Loading source file: /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv
2023-11-13T19:24:17.581Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Scanning source file: /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv
2023-11-13T19:24:17.582Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Scan types: {
2023-11-13T19:24:17.582Z   "exifToolScan": true,
2023-11-13T19:24:17.582Z   "mediaInfoScan": false,
2023-11-13T19:24:17.582Z   "closedCaptionScan": false
2023-11-13T19:24:17.582Z }
2023-11-13T19:24:17.582Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Using cached scan results
2023-11-13T19:24:17.583Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Loaded plugin inputs: {}
2023-11-13T19:24:17.583Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:File has changed, replacing original file
2023-11-13T19:24:17.584Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:{"currentPath":"/temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv","newPath":"/temp-tdarr/test-encode.mkv","newPathTmp":"/temp-tdarr/test-encode.mkv.tmp"}
2023-11-13T19:24:19.588Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Attempt 1: Moving file from /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv to /temp-tdarr/test-encode.mkv.tmp
2023-11-13T19:24:19.589Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Failed to move file from /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv to /temp-tdarr/test-encode.mkv.tmp
2023-11-13T19:24:19.590Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv","dest":"/temp-tdarr/test-encode.mkv.tmp"}
2023-11-13T19:24:19.590Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:{"errno":-2,"code":"ENOENT","syscall":"stat","path":"/temp-tdarr/test-encode.mkv.tmp"}
2023-11-13T19:24:19.591Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:File sizes do not match, input: 62806 does not equal  output: 0
2023-11-13T19:24:19.591Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Attempt 1  failed: Moving file from /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv to /temp-tdarr/test-encode.mkv.tmp
2023-11-13T19:24:19.591Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Attempt 2: Moving file from /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv to /temp-tdarr/test-encode.mkv.tmp
2023-11-13T19:24:19.592Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Failed to move file from /temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv to /temp-tdarr/test-encode.mkv.tmp
2023-11-13T19:24:19.592Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:{"errno":-1,"code":"EPERM","syscall":"copyfile","path":"/temp/tdarr-workDir-node-4H86ZGU59-worker-royal-ray-ts-1699899851117/1699899852482/test-encode.mkv","dest":"/temp-tdarr/test-encode.mkv.tmp"}
2023-11-13T19:24:19.593Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:[-error-]
2023-11-13T19:24:19.593Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Error: ENOENT: no such file or directory, stat '/temp-tdarr/test-encode.mkv.tmp'
2023-11-13T19:24:19.594Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:"ENOENT: no such file or directory, stat '/temp-tdarr/test-encode.mkv.tmp'"
2023-11-13T19:24:19.594Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:"Error: ENOENT: no such file or directory, stat '/temp-tdarr/test-encode.mkv.tmp'"
2023-11-13T19:24:19.595Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:Flow has failed and flow variable flowFailed !== true, running On Flow Fail plugin
2023-11-13T19:24:19.595Z Q24Ic21c7:Node[Gigakiste]:Worker[royal-ray]:[Step W03] [C10] [HEVC Main10 Slow RF23 Lectures Opus Configurable] Running Community plugin: 1.0.0: onFlowError: On Flow Error
```

Here are some full logs:
[tdarr-replace-original-temp-tdarr-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13339640/tdarr-replace-original-temp-tdarr-log.txt)
[tdarr-replace-original-file-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13339489/tdarr-replace-original-file-log.txt)
[tdarr-move-to-original-directory-log.txt](https://github.com/HaveAGitGat/Tdarr/files/13339488/tdarr-move-to-original-directory-log.txt)


Any idea what I could try next?

Thanks

**Comment by janerjak** [comment]
Sorry, this resolved itself. Have been debugging this for a week to no avail, but then another week later it works when I already accepted fate.
Didn't change a thing. Didn't update anything.
