### ISSUE TITLE
Error: spawn git ENOENT when cloning plugins 

### ISSUE THREAD

**Issue by Zixim** [HaveAGitGat/Tdarr#96]
```
Tdarr@tdarr:~/bundle$ MONGO_URL=mongodb://localhost:27017/Tdarr PORT=8265 ROOT_URL=http://localhost/ node main.js
Tdarr started
Tdarr documents folder:/home/Tdarr/Documents
Checking directories
Not running inside a Docker container
Initialising DB
Checking file:1/1
ffmpeg --help
undefined --help
handbrake --help
HandBrakeCLI --help
Commencing file update scan. Deleting non-existent files and adding new files.
Server: Commencing file update scan. Deleting non-existent files and adding new files.
Server: Scanner H4bXYgPP launched
Updating plugins
Cloning plugins
Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Server: Scanner H4bXYgPP:Finished
Server: File scanner exited
```

**Comment by Zixim** [comment]
it needed a  : 
`sudo apt install git-core`
